### ISSUE TITLE
Cannot assign array to property craft\base\FieldLayoutComponent::$uid of type ?string when applying project config

### ISSUE THREAD

**Issue by john-henry** [verbb/hyper#100]
### Describe the bug

Its a Hyper field inside a matrix block

### Steps to reproduce

When applying project config I get the following error

```
 - updating matrixBlockTypes.5cfc3fde-2e14-4d04-812d-45b6360f1f85 ...
error: Cannot assign array to property craft\base\FieldLayoutComponent::$uid of type ?string
```

I have tried moving around fields in button layouts etc to no avail

### Craft CMS version

4.5.9

### Plugin version

1.1.16

### Multi-site?

NO

**Comment by john-henry** [comment]
Interestingly I was able to solve by moving around more links, reordering fields in layouts and resaving.
Which is probably not he best case scenario for me the dev as I don't know why it happened

**Comment by engram-design** [comment]
Hmmm, I'll see how I can reproduce this, but if it happens again, posting your project config Yaml file for your field would be great, as the field layout information is stored in there. I'd like to see how the `uid` got stored as an array...

As this is a Matrix, the Yaml will be stored as a separate file, not in the Matrix's Yaml.

**Comment by john-henry** [comment]
While this was solved for a short time, it came back with this error now. Same yaml and matrix field
[imageAndText--a6742cdf-a1f4-4544-bda0-869c2bf1dfe9.txt](https://github.com/verbb/hyper/files/13318963/imageAndText--a6742cdf-a1f4-4544-bda0-869c2bf1dfe9.txt)


```
- removing matrixBlockTypes.a6742cdf-a1f4-4544-bda0-869c2bf1dfe9.fields.43e939ad-0a36-45d5-ae12-cfa98af1bbda.settings.linkTypes.5.__assoc__.6.1.__assoc__.0.1.0.__assoc__.2.1.1.__assoc__.4.1.__assoc__.3.1.0.__assoc__.0 ...
  - updating matrixBlockTypes.a6742cdf-a1f4-4544-bda0-869c2bf1dfe9 ...
error: Cannot assign array to property craft\fieldlayoutelements\TextField::$autofocus of type bool
```

**Comment by engram-design** [comment]
Strange. Any chance you could export your Matrix field with something like Field Manager and send it through to `support@verbb.io` to see if I can replicate things? 

And just to be clear, the field seems to save fine locally, but when pushing to another environment, and applying the project config, it trips up?

**Comment by engram-design** [comment]
So that might be a slightly different error to the original one, but that should be fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.16"`

**Comment by john-henry** [comment]
Thanks @engram-design I'll give this a go

**Comment by john-henry** [comment]
This looks to be fixed. Thanks
