### ISSUE TITLE
Custom asset fields not saving when using multiple links

### ISSUE THREAD

**Issue by d-karstens** [verbb/hyper#104]
### Describe the bug

Hi, 

We've run into an issue using multiple links where asset fields aren't saving correctly. After a field has been saved once, if we try to add more links only the last one will keep its asset

I've made a short screen recording to demonstrate

https://github.com/verbb/hyper/assets/21274925/bb692e42-8cea-472a-b1fa-cc8c809a2a1d

Let me know if you need any more details,
Thanks!

### Steps to reproduce

1. Create Hyper field with multiple links inside a Vizy field
2. Add a link with an asset and save
3. Add a second link with an asset and save again
4. Asset from the first link is removed

### Craft CMS version

4.5.11.1

### Plugin version

1.1.17

### Multi-site?

No

### Additional context

I wasn't sure if this was a Hyper issue or a Vizy issue, as it only seems to be happening when used in a Vizy field - On Vizy version 2.1.13

**Comment by engram-design** [comment]
Turns out this is a Vizy issue. Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.13"`

**Comment by d-karstens** [comment]
Thanks for the quick fix!

**Comment by engram-design** [comment]
Fixed in [1.1.18](https://github.com/verbb/hyper/releases/tag/1.1.18)
