### ISSUE TITLE
Store additional OEmbed data

### ISSUE THREAD

**Issue by benfeather** [verbb/hyper#105]
### What are you trying to do?

I want to use the Hyper plugin to embed a YouTube video in an entry. Then, I want to retrieve information using GraphQL, such as:

- Thumbnails (YouTube has two thumbnails, maxresdefault.jpg and hqdefault.jpg)
- Thumbnail dimensions (width, height)
- Description
- Embed URL
- Embed Code (iframe)

Currently, this is the output from a Hyper embed:
![output](https://github.com/verbb/hyper/assets/43571410/4305b753-8a4f-40a0-927c-1ea699e2c099)

### What's your proposed solution?

I took a look at the composer file and it seems like the plugin is using the embed/embed package. It would be great if we could get some more data from this package.

![embed-package](https://github.com/verbb/hyper/assets/43571410/edfffe92-f619-43b4-8dd6-b8cd92c31e0e)

**Comment by engram-design** [comment]
We do store a [good bunch](https://github.com/verbb/hyper/blob/a20d4c2fdc8f58406780aac4a8ff4a34c6db90d2/src/links/Embed.php#L74-L89) of data fetched from the embed source, but we don't actually expose that via GraphQL.

I've just added a `linkValue` property which will return that. For example:

```json
{
    "title":"https:\/\/twitter.com\/xkcd\/status\/1619007255327961088",
    "description":null,
    "url":"https:\/\/twitter.com\/xkcd\/status\/1619007255327961088",
    "image":null,
    "code":"<blockquote class=\"twitter-tweet\"><p lang=\"en\" dir=\"ltr\">Code Lifespan <a href=\"https:\/\/t.co\/6sNOmesHxY\">https:\/\/t.co\/6sNOmesHxY<\/a> <a href=\"https:\/\/t.co\/huCUbcmhTc\">pic.twitter.com\/huCUbcmhTc<\/a><\/p>&mdash; Randall Munroe (@xkcd) <a href=\"https:\/\/twitter.com\/xkcd\/status\/1619007255327961088?ref_src=twsrc%5Etfw\">January 27, 2023<\/a><\/blockquote>\n<script async src=\"https:\/\/platform.twitter.com\/widgets.js\" charset=\"utf-8\"><\/script>",
    "authorName":"Randall Munroe",
    "authorUrl":"https:\/\/twitter.com\/xkcd",
    "providerName":"Twitter",
    "providerUrl":"https:\/\/twitter.com",
    "icon":"https:\/\/abs.twimg.com\/responsive-web\/client-web-legacy\/icon-ios.77d25eba.png",
    "favicon":"https:\/\/abs.twimg.com\/responsive-web\/client-web-legacy\/icon-ios.77d25eba.png",
    "publishedTime":null,
    "license":null,
    "feeds":[

    ]
}
```

Just note that this will be a JSON-encoded string, as each provider will return somewhat different data, and the GQL spec doesn't really allow us to return an arbitrary array (it would have to be an interface, and I'd rather not be too heavy-handed with the structure for this data).

Added for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-4 as 1.1.17"`

**Comment by benfeather** [comment]
I've tested the update and it's exactly what I was looking for. Thank you very much for updating it so quickly.

I noticed that when I link a YouTube video, the title is stored in the "text" property and the "title" property is null. Is this intentional? The oEmbed data includes a "title" and a "description", which could be mapped to the "title" and "text" properties.

![title](https://github.com/verbb/hyper/assets/43571410/1860c4a5-342d-48cf-a2ef-fe35cf879734)

For the image property (in the JSON string), it references the hqdefault.jpg, which looks like this for the example above:
https://i.ytimg.com/vi/jfKfPfyJRdk/hqdefault.jpg

This thumbnail isn't ideal, as it includes black bars with a fixed aspect ratio. I know YouTube also supplies a maxresdefault.jpg like so:

https://i.ytimg.com/vi/jfKfPfyJRdk/maxresdefault.jpg

I can extract the hqdefault.jpg path and modify it on the frontend. However, is there a way to get the high-quality thumbnail from the GQL API?

**Comment by engram-design** [comment]
Right, so while there might be some overlap between embed data and Hyper, they're not the same. The `title` from embed data typically wants to be used as the text for the link (hence it mapped to `text`). 

The `title` for a Hyper field is actually the text used for the `title` attribute on the anchor tag. It's arguable that they should be the same, but it's configurable a the link type field layout setting. From what I understand on the UX side of things, it's not recommended to include the `title` attribute if it's the same as the link text - that's just needless duplication.

Mapping the `description` to `title` is an option if you like, I've just enabled that (so long as your field layout contains the "Link Title" field).

As for images, looks like this was changed in the Embed v4 package for performance reasons. But even for v3, I can't seem to get any image returned other than that one. I'm not _overly_ keen on adding provider-specific handling for embeds just for YouTube, as that's a slippery slope.

For v3, the hi-res image is returned, but for v4 it's not. I've added back this functionality for Embed v4, although at a bit of a performance hit. We have to fetch each image found to determine the highest-res version. I'm undecided if this will be the default behaviour or not.

To get this early, run `composer require verbb/hyper:"dev-craft-4 as 1.1.17"`

FYI, either package can be used, as some other plugins require Embed v3 and v4, so there's different handling.

**Comment by benfeather** [comment]
I got confused because both props are "title", but that makes sense now. If I need the title/description I can grab it from the JSON string, so no worries there.

I updated the plugin and it now grabs the highest resolution image using embed v4.

![v4-deps](https://github.com/verbb/hyper/assets/43571410/2ebcda67-7d86-4c37-8603-23d556540f1d)

![v4](https://github.com/verbb/hyper/assets/43571410/49bb6b80-1335-45e9-ab13-5779d95d0c8f)

This is perfect for my use case. Having a higher resolution thumbnail is much more versatile. However, if the performance impact is too significant and it doesn't make it to production, I can handle it on the frontend.

Thank you again for the quick update. I am happy to mark this as solved.

**Comment by engram-design** [comment]
I'm going to place this functionality behind a `resolveHiResEmbedImage` plugin setting. Indeed it _possibly_ can be handled on your front-end, but it'd be nice if you didn't have to. 

As for performance, it's not crazy - for a typical YouTube video, there are only 2 images fetched and compared. However, the default behaviour fetches none at all (just provides the URL), so it'll be up to you on whether that's negligible or not.

**Comment by benfeather** [comment]
Sorry to bring this back to life. Could we get the thumbnail width/height in the linkValue JSON? 
Something like this: 

![image-dim](https://github.com/verbb/hyper/assets/43571410/3984982c-8c34-479c-9e10-7f72d5d6438a)

**Comment by engram-design** [comment]
Likewise, this is going to cause extra fetching on our end, so it's behind the `resolveHiResEmbedImage` config setting.

Updated for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-4 as 1.1.18"`.

**Comment by benfeather** [comment]
Perfect! Thank you very much.
