### ISSUE TITLE
Add a preview for OEmbed links

### ISSUE THREAD

**Issue by benfeather** [verbb/hyper#106]
### What are you trying to do?

It would be helpful to have a preview when using Hyper to link videos via OEmbed.

### What's your proposed solution?

Could you add the option to output a video preview for the link? 

This could be another native field that we could add to the input.

![preview](https://github.com/verbb/hyper/assets/43571410/57cc2e40-49be-4665-940e-f306488150d9)

**Comment by engram-design** [comment]
I like the idea of this being another native field to include so it's not tied to the "Link" field. For example:

<img width="939" alt="Screenshot 2023-12-06 at 8 20 12 pm" src="https://github.com/verbb/hyper/assets/1221575/9a07eb58-8e59-4c4a-9ac7-b5350d6af4e4">

If I were to add the preview on the half-width link field to the left, it would look pretty unbalanced next to the "Link Text".

My immediate concern though, is how to format the preview so as not to take up oodles of the screen or in a too-small area. For example:

<img width="946" alt="Screenshot 2023-12-06 at 8 50 31 pm" src="https://github.com/verbb/hyper/assets/1221575/a29e2c1b-13b1-42c0-9b22-7b8af50e5295">

**Comment by benfeather** [comment]
Is it possible to configure field width in the Craft CP columns layout? The user could limit the preview to one or two columns and use less space.

![link-cols](https://github.com/verbb/hyper/assets/43571410/8fb850a6-ac27-4425-8c39-a335627c30a6)

Another option would be to add a toggle to collapse or expand the preview.

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-4 as 1.1.17"`.

I've also had to do some iframe wrangling to ensure it's responsive. Some providers like YouTube provide it, while others (X/Twitter) don't, and they don't look so hot being full-width, as there's a lot of white space (see above). YouTube on the other hand responds to the width and looks nice.

**Comment by benfeather** [comment]
I've updated the plugin, but I don't see a preview field:

![fields-ver](https://github.com/verbb/hyper/assets/43571410/9706add3-b37a-4b86-a035-771e400e5cce)

![fields](https://github.com/verbb/hyper/assets/43571410/d61b9a9a-c73b-4dd4-8087-c7e93bee2ffe)

**Comment by engram-design** [comment]
Should be under "UI Elements"?

**Comment by benfeather** [comment]
Ah, my mistake! It's there, and it looks great. Thanks again.
