### ISSUE TITLE
"Custom Attributes" no longer saves

### ISSUE THREAD

**Issue by mufi-siebird** [verbb/hyper#110]
### Describe the bug

I am using Hyper version 1.1.20 and it doesnt saves Custom Attributes for link.

### Steps to reproduce

1. Create new Field inside Matrix
2. Add link (any element or normal link)
3. Click on gear icon and add classes and custom attributes
4. Save form.
5. Click on gear icon after reloading page and custom attributes table is completely empty.

### Craft CMS version

4.7.1

### Plugin version

1.1.20

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.20"`

**Comment by engram-design** [comment]
Fixed in [1.1.21](https://github.com/verbb/hyper/releases/tag/1.1.21)
