### ISSUE TITLE
`text` column type is not enough

### ISSUE THREAD

**Issue by gglnx** [verbb/hyper#112]
### Describe the bug

I'm migrating a site, and I've got one entry with 813 links (yeah, I know). It won't save, because the content column is "only" a `TEXT` column (I'm using a MySQL database). Manually changing it to `LONGTEXT` solves it.

### Steps to reproduce

1. Create entry with a fricking too much number of links
2. Try to save it

### Craft CMS version

4.7.1

### Plugin version

1.1.20

**Comment by engram-design** [comment]
Haha, yeah that's a lot of links! Added a setting to control the column type for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.20"`

**Comment by engram-design** [comment]
Fixed in [1.1.21](https://github.com/verbb/hyper/releases/tag/1.1.21)
