### ISSUE TITLE
[dev-craft-5] Link Types Editor Broken

### ISSUE THREAD

**Issue by kylecotter** [verbb/hyper#113]
### Describe the bug

I realize nothing official is out yet, but just putting it on your radar if it's not already:

1. The changes Craft introduced in beta 1 (I believe) of Craft 5 to the field layout editor has impacted Hyper's field layout editor and results in it not functioning.
2. Hyper fields don't init when an entry is triggered from a slideout

Thanks!

### Steps to reproduce

1. Create a new Hyper field, edit field layout for a type - can't drag and drop fields
2. Add hyper field to an entry type, open entry with that entry type from a slideout - Hyper doesn't init

### Craft CMS version

5.0.0-beta.3

### Plugin version

dev-craft-5

**Comment by engram-design** [comment]
Yep, looks like a change from `5.0.0-beta.2` to `5.0.0-beta.3` actually, as it _was_ working! Will sort it out shortly.

**Comment by engram-design** [comment]
Updated in [2.0.0-beta.1](https://github.com/verbb/hyper/releases/tag/2.0.0-beta.1)
