### ISSUE TITLE
Hyper Fieldtype. What is JSON Structure for multiple links using Feed-me.

### ISSUE THREAD

**Issue by goodmixer** [verbb/hyper#114]
### Question

The JSON structure for importing a single link to hyper using Feed-Me
"websiteUrl": {
    "type":"url",
    "linkValue": "www.google.com",
    "linkText": "some text"
}

Works well... but unsure how to structure the JSON for multiple links. Can't find any examples in docs or here.

Any assistance appreciated.

**Comment by engram-design** [comment]
For multiple links, it's just the same, but wrapped in an array.

```
"websiteUrl": [
    {
        "type":"url",
        "linkValue": "www.google.com",
        "linkText": "some text"
    },
    {
        "type":"url",
        "linkValue": "www.google.com",
        "linkText": "some text"
    }
]
```

**Comment by goodmixer** [comment]
Ok. Thanks Josh.
