### ISSUE TITLE
[craft-5] Twig error in field settings

### ISSUE THREAD

**Issue by d-karstens** [verbb/hyper#115]
### Describe the bug

Hi, thanks for all your work on the Craft 5 updates to plugins!

We've just installed the Craft 5 beta version of Hyper and encountered the following twig error when trying to edit a fields settings. I think `columnType` might have been removed in Craft 5?

<img width="1261" alt="Screenshot 2024-03-05 at 10 28 18 am" src="https://github.com/verbb/hyper/assets/21274925/595e84bb-3145-4c04-abeb-d90d444bdf4c">

That's on an old field that was migrated over, when trying to create a new field there's just a "A server error occurred." popup

Thanks!

### Steps to reproduce

1. Try to create a field using version 2.0.0-beta.2
2. Encounter error

### Craft CMS version

5.0.0-beta.5

### Plugin version

2.0.0-beta.2

### Multi-site?

No

**Comment by engram-design** [comment]
Odd. So that's _supposed_ to be taken care of with [this](https://github.com/verbb/hyper/blob/69dd88df61232f3ef0647da1215c97818efc27f3/src/fields/HyperField.php#L84), but I think my last-minute merge brought that back.

Should be fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.0-beta.2"`.

Note there's an outstanding issue I'm working on where link types wont' appear when you first select the field. But, just save the field first, then with the page reloaded the link types should appear.

**Comment by d-karstens** [comment]
That's working now, thanks for the quick fix!

**Comment by engram-design** [comment]
FYI, to track the new field issue https://github.com/craftcms/cms/pull/14526

**Comment by michaeldietiker** [comment]
hi @engram-design

"composer require verbb/hyper:"dev-craft-5 as 2.0.0-beta.2" fixed the issue @d-karstens reported for me as well but now I'm getting:

<img width="2560" alt="Bildschirmfoto 2024-03-07 um 06 41 52" src="https://github.com/verbb/hyper/assets/44356685/b019af8a-9b0b-4103-b0c0-d4c5b92f3b54">

**Comment by engram-design** [comment]
Is that not the same error?

**Comment by michaeldietiker** [comment]
Probably same error, different stack trace?

**Comment by engram-design** [comment]
There should be no more references to `columnType` in the plugin so it seems strange that it’s flagging this. Worth clearing your Craft caches under Utitilities?

**Comment by michaeldietiker** [comment]
Seems to work now. Thanks!

**Comment by ArtDepartmentRF** [comment]
> Note there's an outstanding issue I'm working on where link types wont' appear when you first select the field. But, just save the field first, then with the page reloaded the link types should appear.

**Craft CMS version**
5.0.0-beta.7

**Plugin version**
2.0.0-beta.2

I can save the field without seeing the settings as you describe then as I go back into edit the field I am getting the same error as others above.  I have cleared the cache, but just get the same error.

<img width="1458" alt="image" src="https://github.com/verbb/hyper/assets/25480675/654273a5-fc37-4867-ad4e-87f4368e3107">

<img width="1719" alt="image" src="https://github.com/verbb/hyper/assets/25480675/b9e1e74b-3132-4f5e-bdd1-651e65477d93">

**Comment by engram-design** [comment]
That issue should be solved in Craft 5.0.0-beta.7 (the link types not appearing). Can you confirm?

As for the `columnType` issue, can you triple check you’re on the right plugin version? There are no references to `columnType` anymore.

run `composer require verbb/hyper:"dev-craft-5 as 2.0.0-beta.2"`

**Comment by ArtDepartmentRF** [comment]
> composer require verbb/hyper:"dev-craft-5 as 2.0.0-beta.2"

Running that command and clearing the cache resolved it.  Apologies, misread what you stated earlier.

And yes, now I can see all the fields when creating a new Hyper field type.

Thanks for your help.

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.3](https://github.com/verbb/hyper/releases/tag/2.0.0-beta.3)
