### ISSUE TITLE
[dev-craft-5] Settings panel not working

### ISSUE THREAD

**Issue by stevendierick** [verbb/hyper#117]
### Describe the bug

The setting panel for Hyper fields isn't working. I'm getting an error whenever it opens the panel. Doesn't matter if it's a stand-alone field or inside a Matrix (inline or as cards).

I've recorded it: https://share.cleanshot.com/cLM0yQwWXFJV1ssfNN62

### Steps to reproduce

1. Create Hyper field
2. Add Hyper field to entry type
3. Open entry
4. Add link to Hyper field
5. Click on settings panel button

### Craft CMS version

5.0.0-beta.7

### Plugin version

craft-beta-5 as 2.0.0-beta.2

### Additional context

I thought this might have been related to the [JS modules not loading correctly](https://github.com/craftcms/cms/pull/14526) issue, but it seems to be a different issue?

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.0-beta.2"`.

**Comment by stevendierick** [comment]
Thanks, works perfectly now!

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.3](https://github.com/verbb/hyper/releases/tag/2.0.0-beta.3)
