### ISSUE TITLE
[dev-craft-5] Custom fields can't be added to last link type

### ISSUE THREAD

**Issue by stevendierick** [verbb/hyper#118]
### Describe the bug

When you add a custom field to link types, enabled or disabled, it won't actually add/save that field to the last link type you added it to. So, if you only add a custom field to the `Asset` or `Entry` type, it will not be added/saved. If you add a custom field to `Asset`, `Entry`, and `Phone` it will not be added/saved to `Phone`.

I've recorded a couple of tests:

- https://share.cleanshot.com/rTZRBwHqQSdsfnfkcWd3
- https://share.cleanshot.com/fFHhGFGFmwphNNnjJMJg
- https://share.cleanshot.com/zhYV01sNdFRx0HxY4dSb

### Steps to reproduce

1. Create Field (radio, text,...)
2. Create Hyper field
3. Add field to the link types or last link type
4. Save

### Craft CMS version

5.0.0-beta.7

### Plugin version

craft-beta-5 as 2.0.0-beta.2

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.0-beta.2"`.

**Comment by stevendierick** [comment]
Yes, that fixes it!

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.3](https://github.com/verbb/hyper/releases/tag/2.0.0-beta.3)
