### ISSUE TITLE
Adding variant gives "Variant is missing its product" error

### ISSUE THREAD

**Issue by Antimated** [verbb/hyper#119]
### Describe the bug

I have a hyper field where you can select variants. Whenever I select a variant I get the following error:

![Screenshot 2024-03-21 at 16 55 51](https://github.com/verbb/hyper/assets/2869409/25d7d171-fc6e-4c1f-84ac-7c90fb5b71c3)

I have my own macro that calls `getLinkAttributes()`. Seems like the error is coming from there.
My hyper field also resides inside a static supertable.

![Screenshot 2024-03-21 at 16 56 15](https://github.com/verbb/hyper/assets/2869409/76a559b3-dd1e-4035-882d-09499c29a029)

### Steps to reproduce

1. Create hyper field with variants enabled
2. Select variant and save
3. Error displays

### Craft CMS version

4.8.4

### Plugin version

1.1.22

### Multi-site?

Yes

### Additional context

Supertable is installed

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.22"`

**Comment by engram-design** [comment]
Fixed in [1.1.23](https://github.com/verbb/hyper/releases/tag/1.1.23)
