### ISSUE TITLE
Merge `class` attribute when passing as an argument to `getLink`

### ISSUE THREAD

**Issue by nixondesigndev** [verbb/hyper#12]
### What are you trying to do?

Set the `class` property on the resulting link of `getLink` by passing class as an property i.e. `getLink({ class: 'foo' })`.

Currently this doesn't work and results in `<a href="...">...</a>` rather than `<a href="..." class="foo">...</a>`.

### What's your proposed solution?

When passing `class` to `getLink` i.e `myField.getLink({ class: 'foo' })` it should be merged with any attributes set on the field resulting in a link like so `<a href="..." class="foo">...</a>`.

If the link fields' `classes` property is set to a value e.g. `bar` the resulting link would be `<a href="..." class="foo bar">...</a>`.

Currently the class passed into `$attributes['class']` argument is replaced by `Link::$classes`.

https://github.com/verbb/hyper/blob/03a3bf158e4e4a6501cf6547954a234ffdc2ede8/src/base/Link.php#L420-L424

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.0.3"`

**Comment by engram-design** [comment]
Fixed in [1.0.4](https://github.com/verbb/hyper/releases/tag/1.0.4)
