### ISSUE TITLE
Embed field not usable in Craft 5 beta

### ISSUE THREAD

**Issue by russback** [verbb/hyper#120]
### Describe the bug

See below. Embed enabled with `linkValue` field but field UI is not displaying as expected.

<img width="1337" alt="Screenshot 2024-03-21 at 16 03 36" src="https://github.com/verbb/hyper/assets/2589006/f4720483-ddb6-4b7b-a91d-b53750708810">
<img width="626" alt="Screenshot 2024-03-21 at 16 03 22" src="https://github.com/verbb/hyper/assets/2589006/f7370e91-69fb-433e-9403-9289e3ad0e41">

### Steps to reproduce

1. See field settings in screenshot

### Craft CMS version

5.0.0-beta.10

### Plugin version

2.0.0-beta.3

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed in [2.0.0-beta.4](https://github.com/verbb/hyper/releases/tag/2.0.0-beta.4)
