### ISSUE TITLE
Border radius on `.hyper-body-wrapper` incorrect

### ISSUE THREAD

**Issue by joshuabaker** [verbb/hyper#121]
### What are you trying to do?

The border radius on the `hyper-body-wrapper` class is currently incorrectly set.

![Screenshot 2024-03-21 at 16 56 59@2x](https://github.com/verbb/hyper/assets/160484/450b788a-0c92-43ab-abce-70a5218a5a24)

### What's your proposed solution?

```css
border-radius: 0 0 6px 6px;
```

**Comment by engram-design** [comment]
Appreciate the eye for detail! Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.22"`

**Comment by engram-design** [comment]
Fixed in [1.1.23](https://github.com/verbb/hyper/releases/tag/1.1.23)
