### ISSUE TITLE
Hide `hyper-header` when type cannot be changed and no actions

### ISSUE THREAD

**Issue by joshuabaker** [verbb/hyper#122]
### What are you trying to do?

![Screenshot 2024-03-21 at 16 58 22@2x](https://github.com/verbb/hyper/assets/160484/4df8f3cf-df0f-4e93-8f88-26e35dbb95fd)

### What's your proposed solution?

Please can you hide the `hyper-header` when type cannot be changed and no action can be taken.

**Comment by engram-design** [comment]
Added for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.22"`

**Comment by engram-design** [comment]
Fixed in [1.1.23](https://github.com/verbb/hyper/releases/tag/1.1.23)
