### ISSUE TITLE
Embed doesn’t work (“Cannot unpack array with string keys”)

### ISSUE THREAD

**Issue by joshuabaker** [verbb/hyper#123]
### Describe the bug

I’m getting the same error whilst trying to use an embed link: “Cannot unpack array with string keys”. It looks like every service is impacted.

<img width="856" alt="Screenshot 2024-03-21 at 17 00 10@2x" src="https://github.com/verbb/hyper/assets/160484/e415afb2-8c87-465f-92f3-525d7d269d82">

<img width="857" alt="Screenshot 2024-03-21 at 17 01 18@2x" src="https://github.com/verbb/hyper/assets/160484/bef795c2-b566-4fcf-af42-4e76b1f6ad0f">

### Steps to reproduce

I’m using a fairly simple field setup, limited to just the Embed type…

<img width="1208" alt="Screenshot 2024-03-21 at 17 02 50@2x" src="https://github.com/verbb/hyper/assets/160484/7afc3049-c66d-4a01-aef0-4ccc8f7cb9a7">

### Craft CMS version

4.8.4

### Plugin version

1.1.22

### Multi-site?

No

### Additional context

PHP 8.0.30

**Comment by engram-design** [comment]
Can you let me know if you have any other embed-related plugins installed and their version? We have handling to support  [`wrav/oembed`](https://github.com/wrav/oembed), and [`spicywebau/craft-embedded-assets`](https://github.com/spicywebau/craft-embedded-assets) which use an older version of the `embed/embed` package.

**Comment by joshuabaker** [comment]
Yeah, that makes sense. You mention that there's a fix?

**Comment by engram-design** [comment]
It's not a fix as such, Hyper allows `"embed/embed": "^3.0.0 || ^4.0.0",` but this is determined by what other plugin version constraints there are.  Just trying to figure out which version you're on, due to handling [here](https://github.com/verbb/hyper/blob/d5745e8e1d2d4f678a5a7a298c6038740e7095ec/src/links/Embed.php#L39).

**Comment by engram-design** [comment]
Actually, I'm able to replicate that. Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.22"`

**Comment by engram-design** [comment]
Fixed in [1.1.23](https://github.com/verbb/hyper/releases/tag/1.1.23)
