### ISSUE TITLE
Multiple links broken

### ISSUE THREAD

**Issue by AlexShearcroft** [verbb/hyper#125]
### Describe the bug

After pulling in the latest version 1.1.23 the multiple links feature no longer loads correctly within a Craft entry via the CMS.

### Steps to reproduce

1. Create a Hyper Field Link with Enable Multiple Links enabled. For my instance, I've set a max of 2. Default: Entry. Selected: Category, Entry, URL options.
2. Include the field within a section.
3. Access the entry with this field added and add a new link.
4. Select an option from the dropdown (Entry)
![Screenshot 2024-03-22 at 11 47 16](https://github.com/verbb/hyper/assets/2182037/ca68a3f8-8af2-46ce-9d57-ecebdc1d8451)
5. By default it's not selecting Entry which I selected and not displaying the content to add.
![Screenshot 2024-03-22 at 11 47 22](https://github.com/verbb/hyper/assets/2182037/7c2162d6-61c0-44a6-96e1-deb017942c1b)

If I then refresh the page it will load the options but I still need to change the option from Category to Entry.

This was working before updating to the latest version.

### Craft CMS version

Craft Pro 4.8.4

### Plugin version

1.1.23

### Multi-site?

No

**Comment by engram-design** [comment]
Sorry about that, this should be fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.23"`

**Comment by AlexShearcroft** [comment]
Thanks for the swift response. I can confirm working as expected 👍

**Comment by engram-design** [comment]
Fixed in [1.1.24](https://github.com/verbb/hyper/releases/tag/1.1.24)
