### ISSUE TITLE
Craft 5: Able to submit empty linkValue and linkText when marked as required

### ISSUE THREAD

**Issue by russback** [verbb/hyper#126]
### Describe the bug

Setting required on `linkValue` and `linkText` does not trigger validation.

### Steps to reproduce

1. Create a link field (this was seen on an Entry link).
2. Set required on fields.

### Craft CMS version

5.0.0-beta.10

### Plugin version

2.0.0-beta.4

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.0-beta.4"`.

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.5](https://github.com/verbb/hyper/releases/tag/2.0.0-beta.5)
