### ISSUE TITLE
Typed Link Field Migration Shell Command Failure errors

### ISSUE THREAD

**Issue by tomhewitt2201** [verbb/hyper#128]
### Describe the bug

I've tried to update through the Craft CMS back end and received the following errors:

The shell command "mysqldump --defaults-file="/var/folders/vt/4rd3pv3d1wj2g5l64cd0c9dw0000gn/T/kxvrkymjgzpg.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-tablespaces --single-transaction --no-data --result-file="/Applications/MAMP/htdocs/trh-web-design/web/storage/backups/trh-web-design--2024-03-28-112816--v4.8.6.sql" trh_web_craft && mysqldump --defaults-file="/var/folders/vt/4rd3pv3d1wj2g5l64cd0c9dw0000gn/T/kxvrkymjgzpg.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-tablespaces --single-transaction --no-create-info --ignore-table=trh_web_craft.craft_assetindexdata --ignore-table=trh_web_craft.craft_cache --ignore-table=trh_web_craft.craft_imagetransformindex --ignore-table=trh_web_craft.craft_resourcepaths --ignore-table=trh_web_craft.craft_phpsessions --ignore-table=trh_web_craft.craft_sessions trh_web_craft >> "/Applications/MAMP/htdocs/trh-web-design/web/storage/backups/trh-web-design--2024-03-28-112816--v4.8.6.sql"" failed with exit code 127: sh: mysqldump: command not found

### Steps to reproduce

1. Craft updated to latest version
2. Running on local server, PHP 8.2

Composer plugins: 
        "craftcms/ckeditor": "3.8.2",
        "craftcms/cms": "4.8.6",
        "craftcms/feed-me": "5.4.0",
        "ether/seo": "4.2.2",
        "jalendport/craft-readtime": "2.0.0-beta.1",
        "marknotton/agent": "5.0.0",
        "putyourlightson/craft-sprig": "2.8.0",
        "sebastianlenz/linkfield": "2.1.5",
        "verbb/field-manager": "3.0.8",
        "verbb/hyper": "1.1.25",
        "verbb/super-table": "3.0.12",
        "vlucas/phpdotenv": "^3.4.0",
        "xpertbot/craft-wheelform": "3.1.8"

### Craft CMS version

Craft Solo 4.8.6

### Plugin version

1.1.25

### Multi-site?

No

**Comment by engram-design** [comment]
By default, Hyper tries to backup your database before running the migrations. This is a good idea in general, so I would recommend to either fix the `mysqldump` command not being able to run, or disable the [`backupOnMigrate`](https://verbb.io/craft-plugins/hyper/docs/get-started/configuration) plugin setting.

Note that you're probably going to run into backup failure issues for Craft updates as well, so my recommendation is to fix backups not working, which is for Craft in general.
