### ISSUE TITLE
Add ability to add Form link type

### ISSUE THREAD

**Issue by umkasanki** [verbb/hyper#130]
### What are you trying to do?

Hello.
Add ability to add Form link type if Formie plugin is installed?
Thanks

### What's your proposed solution?

https://github.com/verbb/hyper/assets/496132/14c40cda-fdb9-40a5-b8e5-acf5d4cb7409

**Comment by engram-design** [comment]
Sure! Added for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.25"`

But as forms don't have an inherent URL, it'll be up to you to resolve where it goes.

```twig
{% if entry.hyperFieldHandle.type == 'verbb\\hyper\\links\\FormieForm' %}
    {% dd entry.hyperFieldHandle.getElement().handle %}
{% endif %}
```

**Comment by umkasanki** [comment]
> But as forms don't have an inherent URL, it'll be up to you to resolve where it goes.

Sure. That's what I planned.
Thanks for blazing fast support

**Comment by benoitblancquaert** [comment]
What is the added value of this extra link type since Formie forms have no URLs?

**Comment by engram-design** [comment]
Probably very specific, but there are other cases where linking to elements with no URLs is still needs, like Users. But I don't pretend to understand what @umkasanki is doing in their use case.

**Comment by engram-design** [comment]
Added in [1.1.26](https://github.com/verbb/hyper/releases/tag/1.1.26)
