### ISSUE TITLE
Type dropdown styling is off (Safari, Craft 5)

### ISSUE THREAD

**Issue by amphibian** [verbb/hyper#132]
### Describe the bug

In Safari, the "type" select element is styled oddly with a serif font. Does not look this way in Chrome.

<img width="165" alt="Screenshot 2024-04-02 at 2 18 56 PM" src="https://github.com/verbb/hyper/assets/53333/c00f7ca2-23aa-4dff-96c4-16ec548a7aea">

### Steps to reproduce

1. Make a Hyper field.
2. Look at it via Safari.

### Craft CMS version

5.0.0

### Plugin version

2.0.0-beta.7

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.0-beta.7"`.

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.8](https://github.com/verbb/hyper/releases/tag/2.0.0-beta.8)
