### ISSUE TITLE
Creating Asset-Links programatically

### ISSUE THREAD

**Issue by Soutware** [verbb/hyper#137]
### Question

I tried to do it the same way as in the docs for entries (it works for entries obviously).

But when it saves, it just creates a url link and puts the ID of the asset in there.

So how can you create Asset Links programatically then?

Thanks in advance :)

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.27"`
