### ISSUE TITLE
[5.x] Custom field values not saving

### ISSUE THREAD

**Issue by ZapaNOR** [verbb/hyper#143]
### Describe the bug

I have added 4 color fields to the "advanced" tab on my link types.
When pressing the ... to get the slidout for custom fields, I can set the values, but they do not appear to get saved.

This is with a multi-link field, inside a matrix block / entry type. (nested)

### Steps to reproduce

1. Create a hyper field with support for multiple links.
2. Add custom (color?) fields to the advanced tab
3. Add this field to an entry type inside a matrix
4. Try to save any custom values

### Craft CMS version

5.0.4

### Plugin version

2.0.0-beta.8

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-5 as 2.0.0-beta.8"`

**Comment by gglnx** [comment]
Is this bug also effecting the Craft 4 branch? I've tried to upgrade to 1.1.27 (as it got a maybe related fix), but still some fields are not triggering a save:

https://github.com/verbb/hyper/assets/23519/327217e2-63aa-43b2-99de-79ec7e9e30f8

**Comment by engram-design** [comment]
@gglnx Also fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.27"`

**Comment by engram-design** [comment]
@gglnx Updated in [1.1.28](https://github.com/verbb/hyper/releases/tag/1.1.28)
