### ISSUE TITLE
Link Types is empty!

### ISSUE THREAD

**Issue by ManiakMill** [verbb/hyper#157]
### Hello! I have a problem with links types settings.

- PHP version : 8.2.13
- Database driver & version : 8.2.0
- Image driver & version: 8.2.13
- Craft edition & version: 5.1.4
- Yii version: 2.0.48.1
- Twig version: 3.8.0
- Guzzle version: 7.8.1

<img width="453" alt="image" src="https://github.com/verbb/hyper/assets/2777750/840d15e2-0c9e-4150-b388-6f142101d776">

It's empty. What's wrong with my setup?
Thank you

**Comment by engram-design** [comment]
If you open your Web Developer tools (in Chrome), are there any errors in the console related to JavaScript?

**Comment by ManiakMill** [comment]
> If you open your Web Developer tools (in Chrome), are there any errors in the console related to JavaScript?

Any errors on field page. I used verbb/hyper v.^2.0.  I used now trial mode, maybe this is the problem?

**Comment by engram-design** [comment]
Trial mode is not an issue. So there are no JavaScript errors shown in your Web Developer console? 

Can you also confirm if the JavaScript for Hyper is loading as per the below?

![CleanShot 2024-05-22 at 19 08 31@2x](https://github.com/verbb/hyper/assets/1221575/b8da74fc-ab6d-4e39-9859-fc64734ef456)

**Comment by ManiakMill** [comment]
Its all list of requests...

<img width="753" alt="image" src="https://github.com/verbb/hyper/assets/2777750/56dd3265-b46a-4262-bbec-0fc5b46877c2">

**Comment by engram-design** [comment]
I don't suppose this is on Windows by chance? We had a similar issue with JS not loading for another plugin.

**Comment by ManiakMill** [comment]
Yes it’s windows 11 but I try on server too. Same situation.

**Comment by engram-design** [comment]
This _might_ be related to https://github.com/craftcms/cms/issues/15043#issuecomment-2125637951 if you want to update Craft to confirm?

**Comment by ManiakMill** [comment]
Hello! I update to Craft v. 5.1.7 all works fine now. Thank you

**Comment by ManiakMill** [comment]
Solved.
