### ISSUE TITLE
Reordered link types gets reset on save

### ISSUE THREAD

**Issue by RyanRoberts** [verbb/hyper#16]
### Describe the bug

See the video below:

### Steps to reproduce

https://media.yep.digital/R7r0D1Jt

### Craft CMS version

4.3.10

### Plugin version

1.0.4

### Multi-site?

No

### Additional context

Tested in Firefox Dev Edition and the latest macOS Safari.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.0.4"`

**Comment by engram-design** [comment]
Updated in [1.0.5](https://github.com/verbb/hyper/releases/tag/1.0.5)
