### ISSUE TITLE
Cog icon is displayed for links without any additional tabs

### ISSUE THREAD

**Issue by MoritzLost** [verbb/hyper#162]
### Describe the bug

In reaction to #160 I've removed the second tab from most link types. However, when the field is set to allow only one link, and a link type with only one tab in the field layout tab is opened, the cog icon to the upper right is still displayed. Clicking on it gives you an empty fly-out:

![Screenshot 2024-05-24 at 12 56 17](https://github.com/verbb/hyper/assets/10146880/27a20dcd-7c85-4e42-9213-9fa543d10122)

### Steps to reproduce

1. Set a hyper field to allow only a single link and remove the second tab from any link type.

### Craft CMS version

5.1.6

### Plugin version

2.0.0

**Comment by engram-design** [comment]
Didn't actually notice this change in behaviour for Craft 5. Unlike Craft 4, it seems you can now have empty field layout tabs. This will go away if you also remove the "Advanced" tab.

Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.0"`.

**Comment by MoritzLost** [comment]
@engram-design Not sure if I understand, in my test case I had already deleted the _Advanced_ tab? In any case, looks like the new version fixes this, thanks!

**Comment by engram-design** [comment]
No you were right, testing just after I mentioned that (as I noticed unlike in Craft 4 that tab still existed - thinking it might be the issue). But should indeed all be resolved.

**Comment by engram-design** [comment]
Fixed in [2.0.1](https://github.com/verbb/hyper/releases/tag/2.0.1)
