### ISSUE TITLE
Switching between link types with and without second tabs leaves the cog/ellipsis menu disabled

### ISSUE THREAD

**Issue by MoritzLost** [verbb/hyper#163]
### Describe the bug

Related to #162. When a hyper field is set to allow multiple links, the link UI will show either a cog icon or an ellipsis icon in the upper right, depending on whether the selected link has any additional layout tabs. If switching between link types causes the UI to switch between those two icons (cog and ellipsis), those icons don't do anything any more. Probably a missing event listener?

https://github.com/verbb/hyper/assets/10146880/af9c2700-2d47-475a-a4c9-ba76ccb4e6e0

### Steps to reproduce

1. Create a link field that allows multiple links. Configure one link type with multiple layout tabs, and one link type with only one layout tab.
2. Place the field in an entry field layout and create a new entry.
3. In the UI, switch between the link types and then click on the cog or ellipsis icon.

### Craft CMS version

5.1.6

### Plugin version

2.0.0

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.0"`.

**Comment by engram-design** [comment]
Fixed in [2.0.1](https://github.com/verbb/hyper/releases/tag/2.0.1)
