### ISSUE TITLE
Removing the native field linkText throws an error

### ISSUE THREAD

**Issue by angelokeirsebilck** [verbb/hyper#164]
### Describe the bug

I have a hyper link field where I only have URL as the available link type. Here i only want editors inserting URL's as these are social links.

Removing every native field except linkValue throws an error:

Invalid Argument – [yii\base\InvalidArgumentException](https://www.yiiframework.com/doc-2.0/yii-base-invalidargumentexception.html)
Invalid field: linkText

1. in /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.phpat line 513
2. in /var/www/html/vendor/verbb/hyper/src/base/Link.php at line 440

### Steps to reproduce

1. Create hyper field
2. Only select URL as the available link type
3. Remove all native fields except linkValue
4. Render the field

### Craft CMS version

5.1.7

### Plugin version

dev-craft-5

**Comment by daafbleumink** [comment]
I'm experiencing the same. Following this issue.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.0"`.

**Comment by engram-design** [comment]
Fixed in [2.0.1](https://github.com/verbb/hyper/releases/tag/2.0.1)
