### ISSUE TITLE
Matrix > Super Table > Hyper, field layout changes are lost when switching between link types

### ISSUE THREAD

**Issue by darylknight** [verbb/hyper#17]
### Describe the bug

I have a Matrix field used as a page builder, with a Super Table field inside a block. Inside Super table, there is a Hyper field for buttons. If I remove the "Advanced" group of fields from Hyper on the "Entry" link type, then switch to another link type and back again, the Advanced group of fields has come back again.

https://user-images.githubusercontent.com/1250017/220897312-19458c6f-3f96-4474-b507-67eb84843dd9.mov

### Steps to reproduce

1. Create a Matrix field, add a block with a Super Table field, then add a Hyper field inside Super Table
2. Try to make changes to the field layout designer for a link type, then switch to another link type and back again

### Craft CMS version

4.3.10

### Plugin version

1.0.4

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.0.4"`

**Comment by darylknight** [comment]
Fixed, thank you!
