### ISSUE TITLE
Bug in validation after switching between types

### ISSUE THREAD

**Issue by boboldehampsink** [verbb/hyper#170]
### Describe the bug

I have an issue with Hyper where the field is saved as an URL. I then switch to Entry, select one and save. Then I switch back to URL and put in a new URL, and then this happens:

![image](https://github.com/verbb/hyper/assets/378974/85318304-28e1-454c-812c-401798d3408d)

That validation error makes no sense. As you can see there is only one.

### Steps to reproduce

1. Save as URL
2. Switch to Entry and save again
3. Switch to URL and save again

### Craft CMS version

5

### Plugin version

2

### Multi-site?

Yes

### Additional context

In this case this is happening within a Matrix field. Haven't tested outside of matrix.

**Comment by engram-design** [comment]
I can't seem to replicate that. Can you let me know if you have a value for "Max Links" in the field settings? It's hidden under the "Enable Multiple Links" setting, which I know you have disabled, but there is a bug that it will use the min/max limit settings for non-multi link fields.

**Comment by boboldehampsink** [comment]
@engram-design yeah it has maxLinks: 1

**Comment by engram-design** [comment]
Gotcha, so I believe that should be fixed in [2.0.2](https://github.com/verbb/hyper/releases/tag/2.0.2)
