### ISSUE TITLE
Incorrect oldFieldTypeClass on MigrateTypedLinkField

### ISSUE THREAD

**Issue by lexisother** [verbb/hyper#172]
### Describe the bug

The `$oldFieldTypeClass` on the `MigrateTypedLinkField` class is incorrect. When migrating from Typed Link Field 2.1.5, Hyper tells me "No fields available to migrate", despite having over five different fields. After checking the database table, it came to my attention that the `type` of these typed link fields wasn't `\lenz\linkfield\fields\LinkField` (which is the result of `LinkField::class`), but rather `typedlinkfield\fields\LinkField`.

Changing the migration to reflect this worked like a charm:
```php
    public string $oldFieldTypeClass = 'typedlinkfield\fields\LinkField';
```

### Steps to reproduce

1. Create a couple typed link fields
2. Install Hyper and go to its plugin settings
3. Under migrations, go to the typed link field tab
4. Click the first button to migrate tables
5. A green piece of text appears reading "No fields available to migrate"

### Craft CMS version

4.10.0

### Plugin version

1.1.32

### Multi-site?

No

**Comment by engram-design** [comment]
It **should definitely** be `typedlinkfield\fields\LinkField` and anything else is going to be for an older version of Typed Link that isn't supported. This has been brought up in https://github.com/verbb/hyper/issues/147 and that the Typed Link plugin [migration](https://github.com/sebastian-lenz/craft-linkfield/blob/main/src/migrations/m190417_202153_migrateDataToTable.php) hasn't run properly for whatever reason.

I should warn against just changing the type, as if the migration hasn't actually run properly (for Typed Link) some settings are not going to be the latest for their plugin. Absolutely a bonus if things are working correctly, but their migrations certainly [does some things](https://github.com/sebastian-lenz/craft-linkfield/blob/9262726f295c1cd71ec1529f579055329fcbe45c/src/migrations/m190417_202153_migrateDataToTable.php#L190-L219) on the field settings. For example, I've tried doing this for one install I was testing with and there were errors everywhere.
 
As per my comment in that other thread...

> The solution for now is to use Hyper to get the legacy Typed Link fields up to date, then migrate them to Hyper as normal. We've added a new console command to make this work.

You can run `./craft hyper/typed-link-legacy` which will convert older Typed Link fields to their latest. Once that's done, you can run the Hyper migration as normal.

**Comment by lexisother** [comment]
I guess I got lucky with the migration, since I didn't run into any errors myself after changing the class manually. But I'll keep this in mind for any future sites I migrate. Thanks for the quick pointer.

**Comment by lexisother** [comment]
I redid the entire process because my manual editing of the Hyper migration was probably causing issues after all, they just weren't straight up in my face. Doing everything the correct way by running `craft hyper/typed-link-legacy` first did indeed resolve the problem. Thanks for the help!
