### ISSUE TITLE
Migrating LinkIt fields within Supertable results in empty links

### ISSUE THREAD

**Issue by Ticolyle** [verbb/hyper#173]
### Describe the bug

We have a Matrix page builder field containing a SuperTable with a LinkIt field, and we are migrating all of our link fields to Hyper.

Installing the plugin, and running the field migration works as expected. All LinkIt fields are replaced with Hyper fields and this change is reflected in the project config. Running the content migration for LinkIt shows a long list of green changes, and no errors or exceptions are thrown.

When looking at the content post migration, the Hyper fields associated directly with an Entry, Global Set, or Matrix field all seem to have migrated the existing link content correctly.

However, links within the SuperTable field within a Matrix have empty content. URLs have no characters in text field, Entry links are un-selected, etc. 

### Steps to reproduce

I'm sorry, I am unsure how to suggest reproducing this issue. Our setup:

Matrix > SuperTable > LinkIt (Migrated to Hyper)

LinkIt version: 4.0.4.1

### Craft CMS version

4.10.2

### Plugin version

1.1

### Multi-site?

Yes

### Additional context

I see a couple other issues related to LinkIt or Hyper in the history here. However, we are not seeing any exceptions or errors when we run the content migration.

- https://github.com/verbb/hyper/issues/102
- https://github.com/verbb/hyper/issues/75

Thank you!

**Comment by engram-design** [comment]
Hmm, I can't seem to replicate that, and we do support nested Matrix/Super Table fields. Everything does seem to be migrating correctly for my testing fields.

If you want to check the output of the migration, to check if it has indeed processed the Super Table block, you can inspect the source of your Super Table block in an entry - where your Hyper field is (or your LinkIt field before the migration).

You'll need to look for something like the below:

```
<input type="hidden" name="fields[matrixSuperTableField][blocks][365][fields][superTableField][blocks][477][fields][linkField][0][linkValue]" value="">
```

And you'll be able to see the ID for the Super Table block is `477`. This should correspond to the output for the migration:
```
> Migrated “linkField” Super Table content #46 for element #477
```

If you don't see that, then the block hasn't been processed. You're also welcome to send through your database to `support@verbb.io` (before the Hyper migration) if that's a possibility, and just direct us to where there's some content not correctly migrating across.

**Comment by Ticolyle** [comment]
Thanks very much for the suggestions @engram-design, I will take close look at that and try to get back to you by next week.

Thanks!

**Comment by Ticolyle** [comment]
@engram-design Finally had some time to circle back to this and was able to successfully do the migration as documented this time around. Going to close this issue. 

Apologies for not having a more specific root cause but I think it came down to either my local cache, or some issues with my local copy of the db or project-config. Restarting from scratch got me across the finish line.

Thanks again for your quick response earlier! Appreciate it very much.
