### ISSUE TITLE
Feed Me Support seems broken

### ISSUE THREAD

**Issue by funkysoul** [verbb/hyper#174]
### Describe the bug

So I map all required fields (apart from hyper) a dozen of others. 
every property of hyper as either a default or an imported value. 
While checking out Log files, all seems correct and all values are being carried over to the insert method. 
after import ran, all Link fields are empty. 

Log of an imported item
![Screenshot 2024-07-01 at 13 08 41](https://github.com/verbb/hyper/assets/315914/95b0435d-15a1-4fa0-bced-83da24c147c5)

Feedme Import Settings
![Screenshot 2024-07-01 at 13 14 21](https://github.com/verbb/hyper/assets/315914/939e7113-86f1-4511-a792-ff75645d2d9a)

### Steps to reproduce

No Special "moves", just using feedme as intended and filling Hyper as intended

### Craft CMS version

5.2.4.1

### Plugin version

2.0.2

### Multi-site?

No

**Comment by engram-design** [comment]
The `Type` value is probably going to be the issue here. That should be `url`.

**Comment by funkysoul** [comment]
wth.. i could have sworn that i also tried with lowercase `url`
well.. yes, it worked indeed..
