### ISSUE TITLE
404 Hyper CP Resources

### ISSUE THREAD

**Issue by strandofgenius** [verbb/hyper#178]
### Describe the bug

I've got a site that is getting a `404` trying to reference `/cpresources/376641ee/assets/hyper-ddbaa87a.css` and  `/cpresources/376641ee/assets/hyper-dd8616f8.js`  which doesn't exist in the vendor files. It should be `hyper-df4d1173.css` and `hyper-f0ff8066.js`. We are use blitz and CF, but from what I can tell the cache-control is being respected and I have cleared all cache just to check but unsuccessful at this point.

### Steps to reproduce

Using a standard hyper field and reusing on multiple matrix block entry types.

### Craft CMS version

Craft Pro 5.2.6

### Plugin version

2.0.2

### Multi-site?

no

**Comment by engram-design** [comment]
What's your hosting? Just checking if it's Servd or Craft Cloud, or "regular" hosting?

The hash (`hyper-dd8616f8`) isn't something that we control, and is determined by Craft/Yii's asset bundle generation. If you clear the cache, is it still the same filename it's trying to reference?

And if you take a look in your `/cpresources/376641ee/assets/` folder, those JS/CSS files exists there, but just with a different name? Each time you refresh the cache, are their filenames changed?

**Comment by strandofgenius** [comment]
Our hosting is on AWS. When I clear the cache it is still trying to reference the same filename `hyper-ddbaa87a.css` and `hyper-dd8616f8.js`. I navigated to `/cpresources/376641ee/assets/` and the file there is `hyper-df4d1173.css` and `hyper-f0ff8066.js`. 

When I clear the CP resources cache it does clear the directory on the server. After navigating to an entry to edit the page and check the cpresources path again those same 2 files (`hyper-df4d1173.css` and `hyper-f0ff8066.js`) exists again. So it doesn't look like it isn't regenerating the hash every time the cache is cleared.

Is it supposed to be refreshing every time?

**Comment by strandofgenius** [comment]
Removing the `vender` directory and running `composer install` ended up fixing the issue in the staging environment. Not fully sure what the difference was since composer acted as if there was nothing new to install.

**Comment by engram-design** [comment]
Glad you got it sorted!
