### ISSUE TITLE
Having a Hyper field + a Vizy field creates constant "Showing your unsaved changes" message

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/hyper#179]
### Describe the bug

This took a while to identify but basically if you have on the first tab a Hyper field and a Vizy field, you get that provisional draft message all the time, even after clicking discard etc.
<img width="568" alt="Screenshot 2024-07-27 at 10 20 35" src="https://github.com/user-attachments/assets/eebf5b21-4822-4d38-8e32-b5a7dd93db48">
This is on a fresh install with default Hyper field and Vizy field (no blocks defined).

If you move the Hyper field to a new tab, it works fine again!

### Steps to reproduce

1. Create Hyper field
2. Create Vizy field
3. Put them in the same tab in an entry type
4. Create an entry, then open it and you keep getting the "Showing your unsaved changes" even if you save / discard etc

### Craft CMS version

5.2.8

### Plugin version

2.0.3

### Additional context

Vizy 3.0.1

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.3"` and `composer require verbb/vizy:"dev-craft-5 as 3.0.1"`.

**Comment by sjcallender** [comment]
@engram-design - This is happening within Matrix fields too for me, but only in Firefox (Mac). We're on the latest versions of everything (same site as the other recent "New Order" button issue you helped with).

**Comment by sjcallender** [comment]
Created a new issue since my issue is with Matrix and Firefox only. https://github.com/verbb/hyper/issues/189

**Comment by engram-design** [comment]
Following up in https://github.com/craftcms/cms/discussions/15794

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/hyper/releases/tag/2.1.0), but will need to wait for Craft 5.5 to be released, where they have added their fix.

**Comment by bleepsandblops** [comment]
@engram-design don't know if it's related but big issue here with latest version (2.1.0 and 2.1.1) where if you add a Vizy block that has a Hyper element the screen freezes and then you get this:
<img width="765" alt="Screenshot 2024-10-10 at 16 09 00" src="https://github.com/user-attachments/assets/cedb1115-b277-4627-9839-e94e52d31c8f">

I downgraded Hyper to 2.0.5 and Vizy is on 3.0.4 and problem went away.

**Comment by engram-design** [comment]
More of a Vizy issue that one, but fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-5 as 3.0.4"`.

**Comment by engram-design** [comment]
Fixed in [Vizy 3.0.5](https://github.com/verbb/vizy/releases/tag/3.0.5)
