### ISSUE TITLE
__clone method called on non-object

### ISSUE THREAD

**Issue by darylknight** [verbb/hyper#18]
### Describe the bug

Possibly related to https://github.com/verbb/hyper/issues/17 ?

I really don't have much info here - I just tried to access the editing page for an entry on our staging server which contains a Matrix > Super Table > Hyper field, and got this error. This is inside Craft.

![image](https://user-images.githubusercontent.com/1250017/220905993-792047ed-68db-43c6-8748-e4a2f4a4d645.png)

Let me know what other info I can provide. I'm going to temporarily remove Hyper as this project is in QA and going live in a few days.

### Steps to reproduce

1. Add a Hyper field to a Matrix > Super Table field
2. ??

### Craft CMS version

4.3.10

### Plugin version

verbb/hyper:"dev-craft-4 as 1.0.4"

### Multi-site?

No

**Comment by engram-design** [comment]
Very likely related to https://github.com/verbb/hyper/issues/17 and if you're able let me know if that sorts things for this issue as well.

**Comment by darylknight** [comment]
Yep, seems to be fixed - thank you.
