### ISSUE TITLE
[craft-5] Support fields/merge 

### ISSUE THREAD

**Issue by reilnuud** [verbb/hyper#185]
### What are you trying to do?

Migrating sites, I have a lot of fields to merge now, this feature is realtively new, but we are still holding off on migrating some sites since Hyper fields don't currently support the feature: 

- https://github.com/craftcms/cms/discussions/14554
- https://craftcms.com/docs/5.x/upgrade.html#cleanup-optional-steps

### What's your proposed solution?

Support new field/merge command in Craft 5.

### Additional context

I imagine this is already being worked on, but hoping to have an idea of when we might be able to do this as there are several craft 5 features we are hoping to implement soon on some projects.

**Comment by engram-design** [comment]
It's not on my immediate todo list, but I'll look into what is involved!

**Comment by mikolamin** [comment]
I got this issue as well, it is a blocker to update Craft 5. The fields/merge script compares fields with their settings and Hyper fields have a huge set of settings for each field with different Uids, so the script can't recognize that the Hyper  fields are the same.

Why such a huge and odd structure of settings for each Hyper field?

**Comment by Evgeniy1806** [comment]
I have the same problem about trying to migrate to Craft 5

**Comment by LinneaHarts** [comment]
Adding a request for this

**Comment by reilnuud** [comment]
> It's not on my immediate todo list, but I'll look into what is involved!

@engram-design we're looking at our end-of-year planning and just wanted to see if this is on the roadmap yet or not?

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.5"`.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/hyper/releases/tag/2.1.0)
