### ISSUE TITLE
getLink arguments not behaving as expected

### ISSUE THREAD

**Issue by RandomJo** [verbb/hyper#186]
### Describe the bug

According to the docs for [getLink](https://verbb.io/craft-plugins/hyper/docs/developers/link#methods-1), it says that we can pass attributes to override link data. I assume attributes is in reference to the [table](https://verbb.io/craft-plugins/hyper/docs/developers/link#attributes-2) right above it.

When I pass, `getLink({"text": "Button Text Override"})`, the attribute is overridden as expected. However, it seems like many (if not all) other args are just added as `customAttributes`. I specifically want to add a `urlSuffix` like so: `getLink({"urlSuffix": "?product=Product%20Name"})`. But instead, what I see is an attribute added to our anchor tag: `<a urlsuffix="?product=Product%20Name">`

We also see that `classes` isn't working as expected. We have to use `class`. Also `customAttributes` does not work as expected.

We do see that `linkValue` and `linkText` work as expected.

### Steps to reproduce

1. Pass `urlSuffix` as an arg to `getLink`

### Craft CMS version

5.3.4

### Plugin version

2.0.4

### Multi-site?

No

**Comment by engram-design** [comment]
I can see how the docs are misleading on this point, but when it's referring to attributes here, it's talking about **HTML** attributes, not the attributes of a link object. I've altered the docs to reflect this.

This is why when you're adding those values like `class` and `urlSuffix` they are added as HTML attributes to the link.

If you're wanting to change any of the Link attributes on-the-fly, you can do so via the following:

```twig
{% set link = entry.hyperField %}

{% do link.setAttributes({ urlSuffix: '?product=Product%20Name' }, false) %}

{{ link.getLink() }}
```
Note that you need to have the URL Suffix field included in your field layout for the link type.

**Comment by RandomJo** [comment]
Okay, thanks! I was wondering if it was maybe a misinterpretation of the docs since "attributes" has a few different meanings in context.

**Comment by corneliusio** [comment]
@engram-design I'd like to follow up on this because I'm still running into odd behavior when trying to do this. We have a link helper we use throughout our projects that isn't aligning with this behavior. Could you let me know if I'm missing anything here? When passed an argument such as `[ 'urlSuffix' => '?foo=bar' ]` the attribute simply seems to get ignored.

```php 
function link(LinkCollection|Link|null $button, array $args = [], string $wrap = '', bool $pass_empty = false): string
{
    if (!$button || ($button->isEmpty() && !$pass_empty)) {
        return '';
    }

    foreach ($args as $key => $value) {
        if (in_array($key, static::HYPER_ATTRS)) {
            $button->setAttribute($key, $value);
            unset($args[$key]);
        }
    }

    if (isset($args['prepend'])) {
        $text = $args['linkText'] ?? $args['text'] ?? $button->text;
        $args['text'] = "{$args['prepend']}{$text}";
        
        // Note that neither of these work either.
        // $button->setAttribute('text', "{$args['prepend']}{$text}");
        // $button->setAttribute('linkText', "{$args['prepend']}{$text}");
    }

    if (isset($args['append'])) {
        $text = $args['linkText'] ?? $args['text'] ?? $button->text;
        $args['text'] = "{$text}{$args['append']}";
    }

    $args = array_filter($args, function ($value, $key) {
        return !in_array($key, ['prepend', 'append']);
    }, ARRAY_FILTER_USE_BOTH);

    if (!$button->isEmpty()) {
        return $wrap
            ? sprintf('<%1$s>%2$s</%1$s>', $wrap, $button->getLink($args))
            : strval($button->getLink($args));
    }

    if ($pass_empty) {
        return $wrap
            ? sprintf('<%1$s>%2$s</%1$s>', $wrap, $args['linkText'] ?? $args['text'])
            : $args['linkText'];
    }
}
```

**Comment by corneliusio** [comment]
This is a cleaned up version of the above function that specifically uses `setAttributes()` as suggested and isn't working for us.

```php
function link(LinkCollection|Link|null $button, array $args = [], string $wrap = '', bool $pass_empty = false): string
{
    if (!$button || ($button->isEmpty() && !$pass_empty)) {
        return '';
    }

    $attributes = array_intersect_key($args, array_flip(static::HYPER_ATTRS));
    $args = array_diff_key($args, array_flip(static::HYPER_ATTRS));

    if (isset($args['prepend'])) {
        $text = $args['linkText'] ?? $args['text'] ?? $button->text;
        $args['text'] = "{$args['prepend']}{$text}";
    }

    if (isset($args['append'])) {
        $text = $args['linkText'] ?? $args['text'] ?? $button->text;
        $args['text'] = "{$text}{$args['append']}";
    }

    $args = array_diff_key($args, array_flip(['prepend', 'append']));

    $button->setAttributes($attributes);

    if (!$button->isEmpty()) {
        return $wrap
            ? sprintf('<%1$s>%2$s</%1$s>', $wrap, $button->getLink($args))
            : strval($button->getLink($args));
    }

    if ($pass_empty) {
        $text = $button->linkText ?? $args['linkText'] ?? $args['text'] ?? '';

        return $wrap
            ? sprintf('<%1$s>%2$s</%1$s>', $wrap, $text)
            : $text;
    }
}
```

**Comment by engram-design** [comment]
I believe you need to pass in `false` as the second argument to `setAttributes` which is more of a Craft/Yii-ism about "safe" attributes. Note that `setAttributes()` is a function we inherit from Craft and Yii that just about every model/object extends from. From the Yii docs:

> A safe attribute is one that is associated with a validation rule in the current scenario.

The `urlSuffix` is _technically_ not a safe attribute here because it doesn't have a validation rule associated with it. It's kind of a strange concept to call it "safe" when honestly I feel like any property we define should be safe to set.

Anyway, changing your code to the following will work:

```twig
$button->setAttributes($attributes, false);
```

But we'll add these properties to be safe for best practice (although Craft itself has many instances of setting attributes like the above).

**Comment by corneliusio** [comment]
@engram-design Of course! Man sometimes these yii idiosyncrasies really trip me up. Thanks a ton for the help getting this cleared up, sorry for the miss on my part.
