### ISSUE TITLE
A Duplicate declaration on displayName() in MissingLink.php

### ISSUE THREAD

**Issue by thilan-plato** [verbb/hyper#195]
### Describe the bug

A Duplicate declaration on displayName() in src/links/MissingLink.php
`class MissingLink extends Link implements MissingComponentInterface
{
    // Traits
    // =========================================================================

    use MissingComponentTrait;

    // Static Methods
    // =========================================================================

    public static function displayName(): string
    {
        return Craft::t('hyper', 'Missing Link');
    }

    // Properties
    // =========================================================================

    public ?int $linkSiteId = null;
    public string|array|null $sources = '*';
    public ?string $selectionLabel = null;

    // Static Methods
    // =========================================================================

    public static function displayName(): string
    {
        return Craft::t('hyper', 'Missing Link');
    }
}`

### Steps to reproduce

1. just made a upgrade to craft 5 with the latest Hyper version

### Craft CMS version

5.4.4

### Plugin version

2.0.5

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.5"`.

**Comment by mikewink** [comment]
I did as you said above for a Craft CMS 4 to 5 upgrade and now the backend UI does not render any Hyper fields anymore and the frontend throws an error `Cannot access offset of type verbb\hyper\models\LinkCollection in isset or empty`. I do not get the field data anymore from what I see.

Looks like something is really broken now? I am on Craft CMS 5.4.4.

**Comment by engram-design** [comment]
Can you check your log files at /storage/logs/hyper.log if there are any errors logged?

**Comment by mikewink** [comment]
> Can you check your log files at /storage/logs/hyper.log if there are any errors logged?

Yes, there are:

`
2024-09-18 15:17:38 [ERROR] Hyper is being called before Craft is fully initialized. Ensure all element queries are wrapped with a `Craft::$app->onInit()` check.`
`2024-09-18 15:17:38 [ERROR] ReflectionException: Class "craft\behaviors\CustomFieldBehavior" does not exist in /var/www/html/vendor/yiisoft/yii2/di/Container.php:507
`
`Next yii\di\NotInstantiableException: Failed to instantiate component or class "craft\behaviors\CustomFieldBehavior". in /var/www/html/vendor/yiisoft/yii2/di/Container.php:509`

Followed by a long stack trace and multiple error like this.

**Comment by engram-design** [comment]
Ah right, yep aware of this issue and working on it!

**Comment by engram-design** [comment]
Should hopefully be fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.5"`.

**Comment by mikewink** [comment]
> Should hopefully be fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.0.5"`.

It works again. I will test more and leave more feedback if I find something to report. Thank you. Do you have an idea when you will release the next regular update (2.0.6)?

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/hyper/releases/tag/2.1.0)
