### ISSUE TITLE
error: Cannot assign array to property craft\models\FieldLayout::$uid of type string

### ISSUE THREAD

**Issue by darylknight** [verbb/hyper#20]
### Describe the bug

I tried to make changes to the fields in a Hyper field, then deploy to staging. I'm getting this error message when running migrations:

```
Applying changes from your project config files ...
- removing matrixBlockTypes.5d5e0215-e5bd-499c-a2c5-6a154b8adb43.fields.78921b9a-0b31-4561-ae58-13fd8f49ebe0.settings.linkTypes.0.__assoc__.6.1.__assoc__.0.1.0.__assoc__.4.1.0.__assoc__.0 ... 
  - updating matrixBlockTypes.5d5e0215-e5bd-499c-a2c5-6a154b8adb43 ... 
error: Cannot assign array to property craft\models\FieldLayout::$uid of type string
```

I was trying to find a way to use Hyper to add an alias link to scroll further down the page. To do that, I added the "URL suffix" in the field designer and I think that's what caused this.

![image](https://user-images.githubusercontent.com/1250017/221190118-c482ad9d-7342-4e30-b010-5d2793f34bfa.png)

### Steps to reproduce

I don't know what causes this, sorry. Let me know if you need a database dump / composer files

### Craft CMS version

4.3.10

### Plugin version

"verbb/hyper": "dev-craft-4 as 1.0.4",

**Comment by engram-design** [comment]
Can you let me know the field settings for the Matrix field of UID `5d5e0215-e5bd-499c-a2c5-6a154b8adb43`? Just want to ensure I know the field combination for testing.

Oh, and short of sending your database, can you let me know the contents of the `5d5e0215-e5bd-499c-a2c5-6a154b8adb43` Matrix field's Yaml file? The Hyper field `78921b9a-0b31-4561-ae58-13fd8f49ebe0` might be included in that as well, which something is off about the field layout settings.

**Comment by darylknight** [comment]
Yep - sending you a database backup on Discord now. Field settings for that matrix block / Hyper field:

![image](https://user-images.githubusercontent.com/1250017/221544034-dd2b1af6-76c6-46c2-85a2-5fdddc4b2a77.png)

**Comment by engram-design** [comment]
Think I might've gotten to the bottom of this one, due to some project config shenanigans.

If you'd like to test this before the next release, run `composer require verbb/hyper:"dev-craft-4 as 1.0.4"`. After that, I'd recommend a `./craft project-config/rebuild` to ensure all your fields Yaml files are correct. 

During the rebuild the update, you might see lots of:

```diff
__assoc__:
-0:
+-
  - name
  - Content
-1:
+-
  - uid
  - 19596f8c-d36e-4def-a400-769b699c2f17
-4:
+-
  - elements
  -
    -
      __assoc__:
-       0:
+       -
          - type
          - verbb\hyper\fieldlayoutelements\LinkField
-       1:
+       -
          - attribute
          - linkValue
-       4:
+       -
          - mandatory
          - true
-       5:
+       -
          - autocomplete
          - false
-       10:
+       -
          - autofocus
          - false
```

And take note that the associative arrays **shouldn't** contain the numbers. You'll notice how they're not in sequential order. They should be omitted (the green diffs).

**Comment by darylknight** [comment]
Thanks Josh. I just ran that and got the same error as I mentioned on Discord. Output:

```
❯ composer require verbb/hyper:"dev-craft-4 as 1.0.4"
./composer.json has been updated
Running composer update verbb/hyper
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading verbb/hyper (dev-craft-4 5bc98c7 => dev-craft-4 f8a84aa)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading verbb/hyper (dev-craft-4 f8a84aa)
  - Upgrading verbb/hyper (dev-craft-4 5bc98c7 => dev-craft-4 f8a84aa): Extracting archive
Generating optimized autoload files
73 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php craft install/check && php craft up --interactive=0 || exit 0
Craft is installed.
🔒 Acquiring lock ... done

Checking for pending Craft and plugin migrations ...
No new migrations found. Your system is up to date.

Checking for pending content migrations ...
No new migrations found. Your system is up-to-date.

🔓 Releasing lock ... done
> @php craft install/check && php craft clear-caches/all --interactive=0 || exit 0
Craft is installed.
Clearing cache: Asset caches
Clearing cache: Asset indexing data
Clearing cache: Asset transform index
Clearing cache: Compiled classes
Clearing cache: Compiled templates
Clearing cache: Control panel resources
Clearing cache: Data caches
Clearing cache: SEOmatic frontend template caches
Clearing cache: SEOmatic metadata caches
Clearing cache: SEOmatic sitemap caches
Clearing cache: Temp files
Clearing cache: Twigpack Manifest Cache
No security vulnerability advisories found
❯ ./craft project-config/rebuild
Rebuilding the project config from the current state ... error: Cannot assign array to property craft\models\FieldLayout::$uid of type string
```

**Comment by darylknight** [comment]
Additionally, I now can't sign into the control panel

![image](https://user-images.githubusercontent.com/1250017/221860129-3c0e61ca-9358-478c-b5cf-44b18a485ab9.png)

**Comment by Mosnar** [comment]
Also running into this :(

**Comment by engram-design** [comment]
Confirmed to be fixed from @Mosnar for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.0.4"`

**Comment by engram-design** [comment]
Updated in [1.0.5](https://github.com/verbb/hyper/releases/tag/1.0.5)
