### ISSUE TITLE
Choosing 'New Window' results in rel='["noopener","noreferrer"]'

### ISSUE THREAD

**Issue by bfopma** [verbb/hyper#200]
### Describe the bug

When choosing 'New Window' for a link and using `{{ entry.myLinkField.getLink() }}`, the resulting link is output as `rel='["noopener","noreferrer"]'` instead of `rel="noopener noreferrer"`, as indicated in the documentation.

### Steps to reproduce

1. Create a new Hyper link using the "URL" type
2. Toggle "New Window" on
3. Render the link using `{{ entry.myLinkField.getLink() }}`

### Craft CMS version

5.4.7.1

### Plugin version

2.1.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.1.1"`.

**Comment by engram-design** [comment]
Fixed in [2.1.2](https://github.com/verbb/hyper/releases/tag/2.1.2)
