### ISSUE TITLE
"New Window" toggle not editable after initial save

### ISSUE THREAD

**Issue by bfopma** [verbb/hyper#201]
### Describe the bug

When making changes to an existing Hyper link, any change to the "New Window" toggle is not saved. The originally defined "New Window" state is preserved.

### Steps to reproduce

1. Create a new Hyper Link and leave "New Window" toggled off; save the Entry
2. Edit the Entry and toggle the "New Window" on; save the Entry
3. Edit the Entry and check state of the "New Window" toggle--it will be reverted to 'off'

### Craft CMS version

5.4.7.1

### Plugin version

2.1.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.1.1"`.

**Comment by bfopma** [comment]
Thank you, @engram-design!

**Comment by dmitryvatagin** [comment]
@engram-design I just tried it on Craft CMS 5.4.10.1, Hyper 2.1.2. On multisite version.
When I create a new page the field is working, if I go to the next language, I cannot toggle New window switch. 
Propagation method : Translate for each site.

**Comment by engram-design** [comment]
@dmitryvatagin Seems to be working for me. Do note that you need to provide a value in the field on your other site. As in - toggling just the New Window lightswitch when you either haven't selected an Entry or entered a URL (or whatever your link type is) won't work.

Maybe if you can send through a video of what you're seeing?

**Comment by dmitryvatagin** [comment]
@engram-design with the latests updates with plugin and craft cms it works well. Thank you

**Comment by engram-design** [comment]
Fixed in [2.1.2](https://github.com/verbb/hyper/releases/tag/2.1.2)
