### ISSUE TITLE
Add option to link to Solspace Calendar events

### ISSUE THREAD

**Issue by joostclevis** [verbb/hyper#202]
### What are you trying to do?

It would be nice to have the option to link to items from the Solspace Calendar plugin.

### What's your proposed solution?

Add the option to link to items from the Solspace Calendar plugin.

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-4 as 1.3.2"` or `composer require verbb/hyper:"dev-craft-5 as 2.1.1"`.

**Comment by engram-design** [comment]
Added in [1.3.3](https://github.com/verbb/hyper/releases/tag/1.3.3) and [2.1.2](https://github.com/verbb/hyper/releases/tag/2.1.2)
