### ISSUE TITLE
Different output when dumping hyper link field between two sites

### ISSUE THREAD

**Issue by zhua89cc** [verbb/hyper#204]
### Question

I have two sites both using hyper. We successfully migrated typed link field to hyper on site 1 and in the process of doing so on the second one. We have a component library and heavily use neo on site 1 and vizy on site 2. I've migrated the fields and content locally and now working through our component library formatting methods.  In dumping the output of the hyper field in the already migrated site versus the one i'm trying to migrate in the context of a block in an article i'm seeing a different output. In site 1 I get returned a hyper link collection model instance where as in site 2 (the one i'm currently trying to migrate) I just get returned an array of values that are filled out. Trying to access properties that aren't filled out like link text or using a method like getElement() doesn't work in this scenario where as in site 1 that works because I have the model. 

I could get around this and still query the entry if that's the case but one of the benefits of hyper was just calling getElement method if it was an entry instead of doing another craft entry query with the id. 

I'm scratching my head a little bit as to why because I've now upgraded one site to be on the same craft version and downgraded site 2 to be on the same hyper version as site 1. Is there a reason a block with a hyper field in neo would behave differently than a custom block with a hyper field in vizy?

To Attempt to Recreate

Create a neo field and create a neo block with a hyper field. 
Create a vizy field and create a custom vizy block with a hyper field.

Do a craft dump of each and see if you get different results.

### Additional context

<img width="578" alt="Screenshot 2024-10-17 at 3 56 13 PM" src="https://github.com/user-attachments/assets/c776cae7-d48b-4411-bfdd-2298e6e65293">
<img width="568" alt="Screenshot 2024-10-17 at 3 56 22 PM" src="https://github.com/user-attachments/assets/6cf862f4-334d-4ee6-9140-df45a11385db">

Hyper Version 1.3.1
Craft Version 4.12.4.1
Vizy Version 2.1.22 on Site 2
Neo 4.2.13 on Site 1

**Comment by engram-design** [comment]
So the second screenshot shows a non-normalized, raw value of the field, as stored in the database. It's converted to a LinkCollection object upon normalization of the field. This occurs whenever the field is initialized or saved so it's consistent.

As you've mentioned Neo and Vizy, that might be complicating things. But can you let me know what the field setup is for that second screenshot? It would be unusual for Neo to not normalize the Hyper field content, but I could potentially see Vizy might not (although it should).

**Comment by zhua89cc** [comment]
Thanks Josh. Here are screenshots of the vizy block setup, the hyper link field itself, as well as a craft dump of the whole vizy block so you can see that as well. I just resaved the field to see if it would normalize it and it didn't. I did add the hyper field on the entry level itself and doing a dump compared to the dump of the vizy block shows it normalized so seems localized to it being within a vizy block? ArticleBodyData is a variable set to the vizy field in my twig template. 

`        {% dd(entry.linkItem) %}
`

<img width="381" alt="Screenshot 2024-10-19 at 8 21 30 AM" src="https://github.com/user-attachments/assets/8229afd5-6dc7-4e5c-ac83-9e97d5036224">



`        {% dd(articleBodyData[0]['attrs']['values']['content']['fields']) %}
`

<img width="537" alt="Screenshot 2024-10-19 at 8 21 58 AM" src="https://github.com/user-attachments/assets/4d5c7a02-7a41-461c-be3b-ccc43f77bfb5">



<img width="1098" alt="Screenshot 2024-10-19 at 7 28 39 AM" src="https://github.com/user-attachments/assets/3d6f3f22-c90a-418a-9819-7268fadcfbc7">
<img width="1146" alt="Screenshot 2024-10-19 at 7 30 40 AM" src="https://github.com/user-attachments/assets/bce3c048-02a0-4f7d-b883-ae7190bb258e">
<img width="1371" alt="Screenshot 2024-10-19 at 7 30 46 AM" src="https://github.com/user-attachments/assets/ca3b5044-e4e0-4ec2-bc6a-019c7ebbb202">

**Comment by engram-design** [comment]
Okay, so if you're accessing Vizy content like that:

```
{% dd(articleBodyData[0]['attrs']['values']['content']['fields']) %}
```

Then yes, that will be the raw data for the Vizy field, as stored in the database. You don't _really_ want to access that unless you know what you're doing.

Instead, you'll want to loop through nodes and get the Hyper field for the Vizy Block Type you're after. That's going to be normalized.

```
{% for node in entry.vizyField.all() %}
    {% if node.type == 'vizyBlock' and node.handle == 'hyperBlockType' %}
        {{ dump(node.hyperField) }}
    {% endif %}
{% endfor %}
```

**Comment by zhua89cc** [comment]
Thanks! This is helpful for best practice. Seems like i've been accessing all my fields in vizy blocks this way. But generally it hasn't made a difference until the use of hyper exposed this.

**Comment by engram-design** [comment]
Yeah, so any simple fields where you just want the content, using the raw values really isn't an issue. But for any advanced fields like Matrix, Element field, Hyper, and many more - you'll want to ensure that field normalized its content before dealing with it.
