### ISSUE TITLE
Option to hide the site menu in entry selection modal

### ISSUE THREAD

**Issue by f-elix** [verbb/hyper#205]
### What are you trying to do?

I noticed some editors making the mistake of selecting entries from another site in a Hyper field. Craft entries fields have the option to show the site menu (hidden by default), but I'm not seeing the same thing for Hyper.

### What's your proposed solution?

It would be great if we could hide it to make sure that all selected entries are from the current site.

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-4 as 1.3.3"` or `composer require verbb/hyper:"dev-craft-5 as 2.1.2"`.

**Comment by f-elix** [comment]
Thank you so much!

**Comment by engram-design** [comment]
Added in [1.3.4](https://github.com/verbb/hyper/releases/tag/1.3.4) and  [2.2.0](https://github.com/verbb/hyper/releases/tag/2.2.0)
