### ISSUE TITLE
Converting typed link field - enable all doesn't get converted correctly

### ISSUE THREAD

**Issue by bartdigitalpulse** [verbb/hyper#206]
### Describe the bug

I noticed that all the link fields where "enable all" was selected are converted to "none" in Hyper. Can't select anything.  See attached screenshots. 

Linkfield:
![HUcdxEDs44](https://github.com/user-attachments/assets/b3710508-93d9-4c7e-b16d-4dac13bbaba8)

Hyper:
![LzK6uQaHlP](https://github.com/user-attachments/assets/0127e3f8-b8b3-4f86-86b6-30b0d2044b09)

### Steps to reproduce

I upgraded a project from craft 3 to 4. Replaced Typed Link Field with Hyper. Did the all the needed commands:
craft project-config/rebuild, 
craft hyper/typed-link-legacy, 
craft hyper/migrate/typed-link-field, 
craft hyper/migrate/typed-link-content

Needed a project-config/apply --force afterwards because some fields were still showing as typed link field in the cp. 

### Craft CMS version

Craft Pro 4.12.8

### Plugin version

1.3.3

### Multi-site?

Yes

### Additional context

Typed Link Field version is 2.1.5

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-4 as 1.3.3"`.

**Comment by engram-design** [comment]
Fixed in [1.3.4](https://github.com/verbb/hyper/releases/tag/1.3.4)
