### ISSUE TITLE
Update V1 Doc for Content Migration Console Commands

### ISSUE THREAD

**Issue by zhua89cc** [verbb/hyper#207]
### What are you trying to do?

Hi,

Just incase anyone else is illiterate like I am, In the docs the console command to run the content migration is just for link fields. In my case I was trying to migrate from typed link field (lenz). Running it via the UI locally worked because it hits the right migration class but perhaps you could update the v1 docs to differentiate the console commands based on what link field we're trying to migrate from? Because I was testing in staging, allow admin changes were off so I was accidentally running ./craft hyper/migrate/link-content when I should've been running ./craft hyper/migrate/typed-link-content. 

### What's your proposed solution?

Update the v1 doc to list the different link content migration commands based on what we're migrating from.

**Comment by engram-design** [comment]
There are 3 separate pages, each for a different plugin:

- [Migrating from Typed Link](https://verbb.io/craft-plugins/hyper/docs/v1/guides/migrating-from-typed-link)
- [Migrating from Linkit](https://verbb.io/craft-plugins/hyper/docs/v1/guides/migrating-from-linkit)
- [Migrating from Link](https://verbb.io/craft-plugins/hyper/docs/v1/guides/migrating-from-link)

So I'm not quite sure I follow. The [Migrating from Typed Link](https://verbb.io/craft-plugins/hyper/docs/v1/guides/migrating-from-typed-link) page has the correct console commands of `./craft hyper/migrate/typed-link-field` and `./craft hyper/migrate/typed-link-content`

**Comment by zhua89cc** [comment]
That's embarassing, I totally didn't see the other pages!
