### ISSUE TITLE
Migration error for TypedLinkField

### ISSUE THREAD

**Issue by anita-chouhan** [verbb/hyper#208]
### Describe the bug

I am using Hyper to migrate the data from TypedLinkField on the Craft 4 version of CMS. I am getting the _field limit too big error_ for one of the fields during the field migration process.

### Steps to reproduce

1. Create a matrix field with a _Link Field_ in the matrix blocks.
2. Add the matrix field to several entries and add data.
3. Use _Hyper_ to migrate the data from the _Typed Link Field_.
   a. Run `./craft hyper/migrate/typed-link-field` command for migration.

### Craft CMS version

5.11.5

### Plugin version

1.3.3

### Multi-site?

No

### Additional context

**Field settings**
- Default link type: Entry
- Default link text: -
- Custom link text:
   - Allow custom link text (checked)
 - Maximum length: 0
 - Link target:
    - Allow links to open in new window (checked)
 
**Error Image**
Exception: {"link_caption":{"charLimit":["Field Limit is too big for your chosen Column Type."]}} 

<img width="672" alt="Screenshot 2024-11-07 at 6 57 42 PM" src="https://github.com/user-attachments/assets/97594802-7001-4b35-b204-ad8e4303905a">

**Comment by engram-design** [comment]
This would be the first time seeing this error, and seems to relate to a Plain Text field in the Matrix block. What is your `link_caption` field in your Matrix block? There error is being thrown in the Hyper migration because it's going to try and save the Matrix field to update its nested fields.

Does saving the Matrix field manually before migrating to Hyper throw this error?

**Comment by anita-chouhan** [comment]
Hello @engram-design, I managed to figure out the field causing the error. It was indeed a Plain Text field in the Matrix block. The plain text field was set to use a _Field Limit_ of 250 characters and _Column Type_ was set to _varchar_. I updated its column type to _Automatic_  and tried again. The field conversion and content migration were successful. Thanks for the nice migration functionality.

<img width="760" alt="Screenshot 2024-11-08 at 4 21 53 PM" src="https://github.com/user-attachments/assets/8e09249b-0805-4241-9aa4-939a7ec4c6ed">

**Comment by anita-chouhan** [comment]
I noticed another issue after the migration. There are failed jobs in the _Queue Manager_  on updating the value of migrated fields.

<img width="628" alt="Screenshot 2024-11-08 at 5 23 47 PM" src="https://github.com/user-attachments/assets/09a017d6-4409-4d75-bc14-f2bbfedc6163">
