### ISSUE TITLE
Changing the handle of a hyper field returns an empty object in GraphQL

### ISSUE THREAD

**Issue by benfeather** [verbb/hyper#209]
### Describe the bug

I have a Hyper field I want to reuse across multiple entries. When I change the field handle on the entry, the GraphQL request returns an empty object.

Using the default handle:
![hyper-works](https://github.com/user-attachments/assets/03160d7f-8e97-4b7e-a3d4-aae516886bed)

After changing the handle on the entry:
![hyper-handle](https://github.com/user-attachments/assets/7954c819-86bd-41be-8057-76a52e37ed67)
![hyper-not-working](https://github.com/user-attachments/assets/ae73ac8c-ac89-41c0-b643-f3266565df18)

### Steps to reproduce

1. Create a hyper field
2. Add the field to an entry and edit the handle
3. Request the entry in GQL

### Craft CMS version

5.4.9

### Plugin version

2.1.2

### Multi-site?

Yes

**Comment by engram-design** [comment]
Hmm, seems to be all working on my end. Maybe worth clearing some caches between a rename?

<img width="1321" alt="Screenshot 2024-11-08 at 9 03 37 pm" src="https://github.com/user-attachments/assets/7aaab2be-ff64-4247-91dd-ba2082df04db">
<img width="840" alt="Screenshot 2024-11-08 at 9 03 45 pm" src="https://github.com/user-attachments/assets/e17aefcc-ec93-4061-936d-a1b59311b894">
<img width="1328" alt="Screenshot 2024-11-08 at 9 05 08 pm" src="https://github.com/user-attachments/assets/7c5badfd-d091-4730-af8a-8d3bf4e8f09e">

**Comment by benfeather** [comment]
I see where I went wrong; I used the field type for a fragment instead of the Hyper GQL interface, so when I changed the field's handle, the type no longer worked.

My bad!
