### ISSUE TITLE
Once used fields can't be deleted

### ISSUE THREAD

**Issue by gglnx** [verbb/hyper#21]
### Describe the bug

I created a test field, used in a Hyper fieldset, but removed it. If I now try to delete the field I get the following response:

> "Calling unknown method: verbb\\hyper\\services\\Service::handleDeletedBlockType()"

### Steps to reproduce

1. Create a field
2. Assign to a Hyper fieldset
3. Remove it afterwards
4. Try to delete the field

### Craft CMS version

4.3.10

### Plugin version

dev-craft-4

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.0.4"`

**Comment by gglnx** [comment]
Works, thank you! :)
