### ISSUE TITLE
Unsaved changes to hyper field when changing tab in entry type.

### ISSUE THREAD

**Issue by mikesnoeren** [verbb/hyper#213]
### Describe the bug

I have an entry setup with a matrix field in the 'Content' tab. The matrix field contains a block 'buttons', where users can add buttons (which are hyper fields). When these are anywhere in the matrix field, switching tabs at the top of the page (going from 'Content' to 'SEO', renders the hyper fields as changed. Even though they were not touched.

Please see attached video:
https://github.com/user-attachments/assets/9c6dbff3-5d31-414c-9406-b8c81ebe3793

### Steps to reproduce

1. Create matrix with a block that contains a hyper field
2. Fill the field in an entry
3. Switch to a different tab
4. See message for unsaved changes.

### Craft CMS version

5.5.2

### Plugin version

2.2.0

### Multi-site?

No

**Comment by engram-design** [comment]
Originally raised in https://github.com/verbb/hyper/issues/189#issuecomment-2484465839 can you check out the dev branch to see if that's working for you?

To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.2.0"`.

**Comment by idleog** [comment]
I have the same problem, I am now on dev-craft-5 as 2.2.0 and CraftCMS 5.5.3,
On entries which were ok before, it now does not happen anymore. But on entries having this problem before updating hyper, the problem still exists.

**Comment by engram-design** [comment]
Fixed in [2.2.1](https://github.com/verbb/hyper/releases/tag/2.2.1)
