### ISSUE TITLE
Styling issue with 'inner' handles

### ISSUE THREAD

**Issue by mikesnoeren** [verbb/hyper#214]
### Describe the bug

Field handles (made visible by enabling: "Show field handles in edit forms"), don't have proper styling for the inner linkText and linkValue properties. Please see attached screenshot.
![Screenshot 2024-11-20 at 09 29 14](https://github.com/user-attachments/assets/ff9aeac6-34b2-4314-bd5c-fab78a77b13c)

### Steps to reproduce

1. Add hyper field anywhere
2. Enable "Show field handles in edit forms" on your profile
3. Go to hyper field and look at the handles

### Craft CMS version

5.5.2

### Plugin version

2.2.0

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.2.0"`.

**Comment by engram-design** [comment]
Fixed in [2.2.1](https://github.com/verbb/hyper/releases/tag/2.2.1)
