### ISSUE TITLE
Wrong valueType for field

### ISSUE THREAD

**Issue by gglnx** [verbb/hyper#22]
### Describe the bug

Current Hyper defines `string|null` as `valueType()`, but it should be `LinkCollection|null`.

In general, typings could be improved. Currently, `LinkInterface` defines no common methods. If `LinkInterface` had all basic link methods defined, [generics](https://phpstan.org/blog/generics-in-php-using-phpdocs) could be used in `LinkCollection` (as in `ElementCollection` in Craft):

```php
/**
 * @template TKey of array-key
 * @template TValue of LinkInterface
 */
```

The most luxury version would be to define the methods of `LinkInterface` as `@method` in `LinkCollection`, so the magic methods on the first link in collection could be autocompleted too. Maybe to unify the DX with Craft I would also add `one()` and `all()` to `LinkCollection`.

### Steps to reproduce

See `src/fields/HyperField.php` line 40

### Craft CMS version

4.3.10

### Plugin version

dev-craft-4

**Comment by engram-design** [comment]
Good call on `valueType()`, I must've missed that along the way. And `LinkInterface` being empty was certainly me being a bit lazy and waiting until I was fully happy with the `Link` structure.

As for `Collections`, I'm still getting up to speed on all that as I have yet to use them. But happy to do what I can to improve the DX for those who use auto-completion.

**Comment by engram-design** [comment]
Updated in [1.0.5](https://github.com/verbb/hyper/releases/tag/1.0.5)
