### ISSUE TITLE
Cannot delete link where the "Enable Multiple Links" setting is enabled

### ISSUE THREAD

**Issue by Antimated** [verbb/hyper#25]
### Describe the bug

Clicking this delete button:

![Screenshot 2023-02-28 at 15 51 20](https://user-images.githubusercontent.com/2869409/221889714-d7dac522-93d6-4cf4-b2c7-b22e44692134.png)

gives the following error in the console:

<img width="439" alt="Screenshot 2023-02-28 at 15 51 57" src="https://user-images.githubusercontent.com/2869409/221889919-f07a17b5-9b62-4f3e-a90d-5c39ce6da084.png">

![Screenshot 2023-02-28 at 15 52 25](https://user-images.githubusercontent.com/2869409/221890079-41dd43cc-7a34-4798-93fd-71af8afa41c2.png)

Seems like `this.tippy` isn't defined at this point.

### Steps to reproduce

1. Click the delete button
2. Link is not deleted

### Craft CMS version

4.3.10

### Plugin version

1.0.4

### Multi-site?

No

### Additional context

Seems like the layout also breaks when adding multiple links
![Screenshot 2023-02-28 at 16 05 15](https://user-images.githubusercontent.com/2869409/221893636-5eb7c3d7-fd7e-423f-b02f-82a86a502441.png)

**Comment by engram-design** [comment]
Good call, this was due to multi-link fields with a single tab in their field layout. Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.0.4"`

**Comment by engram-design** [comment]
Updated in [1.0.5](https://github.com/verbb/hyper/releases/tag/1.0.5)

**Comment by Antimated** [comment]
@engram-design now I have no delete button (there is no cog to select the delete option from). Seems like the settings cog only is displayed if the tabCount is greater than 1 and the block is not a static block (I presume static means a non multiple select hyper field).

I think the cog with at least the delete option should always show no? Because:

1) If you change from multiple to a single hyper link you should still be able to remove the extra links you created previously
2) If you have a static hyper link you should still be able to delete the link (or set the link type as "No link" (this might be another feature tbh)).

![Screenshot 2023-03-01 at 08 50 55](https://user-images.githubusercontent.com/2869409/222077081-16d273f3-8e8e-4b68-9502-4d2f8b622dcc.png)

**Comment by engram-design** [comment]
Good call, fixed in [1.0.5.1](https://github.com/verbb/hyper/releases/tag/1.0.5.1).

You raise a good point with multi-to-single, and related to https://github.com/verbb/hyper/issues/8 I want to come to a solid decision on that first as to whether to add a "delete" for a single-link field. It's consistent behaviour when dealing with multi and single link blocks for the user, but not sure how that's going to sit with me.

Will be improving it.

**Comment by Antimated** [comment]
@engram-design Sorry to bother you again but if have a single hyper field with no settings panel you still can click the cog wheel and it opens an empty panel (as I have no fields to display in the panel)

![Screenshot 2023-03-01 at 09 36 37](https://user-images.githubusercontent.com/2869409/222086982-3cf3528d-8793-4e0c-a8a4-293ce78454f1.png)

![Screenshot 2023-03-01 at 09 37 53](https://user-images.githubusercontent.com/2869409/222087072-04d65698-0a48-46dd-99b6-2644df6ee64e.png)

![Screenshot 2023-03-01 at 09 38 50](https://user-images.githubusercontent.com/2869409/222087283-9875c5e8-e0e5-40a5-837e-3b9f2a8c9e9d.png)

**Comment by engram-design** [comment]
Should be fixed properly in [1.0.5.2](https://github.com/verbb/hyper/releases/tag/1.0.5.2)
