### ISSUE TITLE
Disable "Embed" as an option when you migrate from Typed Link Field

### ISSUE THREAD

**Issue by darylknight** [verbb/hyper#26]
### Describe the bug

I've just run the auto migration from Typed Link Field to Hyper, and it looks like it enables the "Embed" link type by default. Embed isn't an option in Typed Link FIeld, so it would probably make sense to disable it by default when you migrate away from it.

### Steps to reproduce

1. Migrate a site from Typed Link Field to Hyper

### Craft CMS version

4.3.10

### Plugin version

1.0.5

### Multi-site?

No

**Comment by engram-design** [comment]
Updated for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.8"`

**Comment by engram-design** [comment]
Updated in [1.1.9](https://github.com/verbb/hyper/releases/tag/1.1.9)
