### ISSUE TITLE
Adding custom field to Link Fields results in PHP error

### ISSUE THREAD

**Issue by superflausch** [verbb/hyper#28]
### Describe the bug

Installation and basic field setup work as expected.

But as soon as I add a custom field to the Link Fields and save the changes the action ends after a couple of seconds with a PHP error.

`PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 2097160 bytes) in /var/www/html/vendor/yiisoft/yii2/di/Container.php on line 408`

After that the whole website/craft installation is broken and every request ends with the same error.

### Steps to reproduce

1. Install Plugin
2. Create field
3. Add custom field to layout
4. Save

### Craft CMS version

4.3.10

### Plugin version

1.0.5.2

### Multi-site?

Yes

**Comment by engram-design** [comment]
How large is your project config? It sounds like it might be having trouble generating the Yaml files for your project config. At least that's how I've run into issues like this before - not with Hyper specifically though.

For example, if you add the following to your `config/app.php` file, which disables saving the project config to Yaml files (just to test), I'd be interested if the error still persists?

```php
return [
    // ...

    'components' => [
        'projectConfig' => function() {
            $config = \craft\helpers\App::projectConfigConfig();
            $config['writeYamlAutomatically'] = false;
            return Craft::createObject($config);
        },
    ],
];
```

**Comment by gglnx** [comment]
I've the same error. Disabling writing of YAML files didn't help. I think this commit is the source: https://github.com/verbb/hyper/commit/f8a84aa6c876007556008f752417438e51603ec5 If I pin Hyper to the previous commit, everything works. Looks like endless loop.

**Comment by engram-design** [comment]
Hmm, I'll see if I can replicate it. Anything to note about your Hyper field? Is it in a Matrix for example?

**Comment by gglnx** [comment]
Yes, I have Hyper fields inside Matrix fields too. Do you want a copy of my project configuration?

**Comment by engram-design** [comment]
Might help @gglnx - or a copy of your `fields` database table. Feel free to send to `support@verbb.io`.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.0.5.2"`

**Comment by engram-design** [comment]
Updated in [1.1.0](https://github.com/verbb/hyper/releases/tag/1.1.0)

**Comment by superflausch** [comment]
This resolved the issue for us as well. Cheers.
