### ISSUE TITLE
No assets are available for selection

### ISSUE THREAD

**Issue by darylknight** [verbb/hyper#30]
### Describe the bug

I just added "Asset" as a link type to a Hyper field (which is inside a Matrix block, if it matters). When I click "Choose" for the link, I get the Assets selection modal popup showing all the correct volumes, but they're all empty so I can't select the file I want to link to.

### Steps to reproduce

1. Add an asset link
2. Try to select an asset

Button:
![image](https://user-images.githubusercontent.com/1250017/222767789-e76b4f1f-e438-4562-9ef3-940a195e2bac.png)

Asset modal:
![image](https://user-images.githubusercontent.com/1250017/222767872-b9480e41-bf6e-475f-ae05-41e659a12e71.png)

Actual contents of the Files volume:
![image](https://user-images.githubusercontent.com/1250017/222767919-d4a1f593-bdd3-401c-b04c-7e418070b6f1.png)

### Craft CMS version

4.3.10

### Plugin version

1.0.5

**Comment by mckenzieclark** [comment]
Was just about to post the same issue. Happening here too, but with a standard field i.e. outside of Matrix.

Craft 4.3.10
Hyper 1.0.5.2

**Comment by mckenzieclark** [comment]
The main difference I can see between Hyper's XHR call to `/admin/actions/element-indexes/get-elements` and the regular Assets field is that Hyper doesn't include a 'condition' in the request payload. A call from an Assets field includes the below. Not sure if that has any real effect mind you...

```
"condition": {
    "elementType": "craft\\elements\\Asset",
    "fieldContext": "global",
    "class": "craft\\elements\\conditions\\assets\\AssetCondition",
    "conditionRules": []
}

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.0.5.2"`

**Comment by engram-design** [comment]
Updated in [1.1.0](https://github.com/verbb/hyper/releases/tag/1.1.0)
