### ISSUE TITLE
Embed Links Don't Save

### ISSUE THREAD

**Issue by kylecotter** [verbb/hyper#31]
### Describe the bug

When using an Embed link type, pasting in a URL to the Link field and saving the entry does not save the link url. Other fields within the Embed link type are saved successfully.

### Steps to reproduce

1. Use an Embed link type
2. Paste a URL into the Link field
3. Save
4. URL is not saved

### Craft CMS version

Craft CMS 4.4.0-beta.4

### Plugin version

Commit 9948e76 as 1.0.5.2 (to get around PHP infinite loop)

### Multi-site?

No

**Comment by engram-design** [comment]
When you paste the link, do you see the loading spinner? What sort of link are you adding?

<img width="309" alt="image" src="https://user-images.githubusercontent.com/1221575/222834329-5ff73ef4-d7c4-4d3f-aa7f-983d1345ca9d.png">

**Comment by kylecotter** [comment]
Used the youtube video from the docs to test - https://www.youtube.com/watch?v=jfKfPfyJRdk

I see the spinner, but nothing happens after.

On two projects, one Craft 4.3.10 and one the 4.4 beta, I see the spinner, see the request to `/actions/hyper/fields/preview-embed` and it returns `null` on each.

Ironically, using https://github.com/nystudio107/spin-up-craft in a Codespace and installing Hyper with the same configuration works as expected with the embed data returning and saving.

I'll try and dig a bit deeper on any discrepancies between these local projects. Even with all plugins disabled except Hyper it's not working on those two, so not seeing anything obvious.

**Comment by kylecotter** [comment]
Welp, sorry for wasting your time.

Turns out having the Embedded Assets package installed requires `embed/embed` `^3`.

Removing that allows Hyper to install `embed/embed` `^4` and now embeds are saving properly.

I see Hyper supports `embed/embed` `^3` or `^4` but using `^4` was what got it working for me.

PHP 8.1.16 for what it's worth.

Thanks!

**Comment by engram-design** [comment]
Ah, I see - that's good to know. I'll see what I can do about that to handle both versions.

**Comment by pl-mnm** [comment]
I have faced the same issue, removing the conflicting `embed/embed ^3` requirement also fixed it for me on Craft `4.4.15`.
