### ISSUE TITLE
When clicking the re-order handle when dealing with multiple links, selectize dropdowns re-init themselves

### ISSUE THREAD

**Issue by kylecotter** [verbb/hyper#32]
### Describe the bug

I have a custom field within an Embed link type. The Hyper field accepts multiple links. The custom field is a dropdown. When attempting to reorder multiple links using the handle icon, the dropdown field using selectize duplicates iteself.

![SCR-20230303-i2f](https://user-images.githubusercontent.com/505894/222793988-c3ec669d-3b8f-4855-b0d7-2ae48ddf51d7.png)

### Steps to reproduce

1. Add a custom dropdown field to a Hyper field
2. Allow the field to have multiple links
3. Attempt to reorder the links
4. See UI duplicate itself on custom dropdown field

### Craft CMS version

Craft CMS 4.4.0-beta.4

### Plugin version

Commit 9948e76 as 1.0.5.2 (to get around PHP infinite loop)

### Multi-site?

No

### Additional context

Selectize was added to CP dropdown fields and similar in Craft 4.4 https://github.com/craftcms/cms/discussions/8403

**Comment by engram-design** [comment]
Yeah, this would be the serialization we have to do to save the DOM when re-ordering the link blocks to play nicely with Vue's reactivity. I'll look into it.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.0.5.2"`

**Comment by engram-design** [comment]
Updated in [1.1.0](https://github.com/verbb/hyper/releases/tag/1.1.0)
