### ISSUE TITLE
When a Hyper field allows multiple links, and only one link type is allowed, streamline the "Add a link" process

### ISSUE THREAD

**Issue by kylecotter** [verbb/hyper#33]
### What are you trying to do?

When dealing with multiple links and only one allowed link type, instead of having to click a dropdown to add the only available link type, I would like to be able to click "Add a link" (ideally it'd be labelled "Add an embed" or whatever the one link type is) and save a click.

![SCR-20230303-i6i](https://user-images.githubusercontent.com/505894/222794828-a27163e8-96cf-40fd-9277-58e4cbeb5f0b.png)

### What's your proposed solution?

If only one link type is allowed, remove the click -> dropdown and make the button click add the link.

### Additional context

Loving this plugin so far for regular links! Wanted to try and drop using Embedded Assets too, hence the singular use case of one Embed link type for this field.

**Comment by engram-design** [comment]
Yeah, I have considered this, the issue really is only language! I can change the button to "Add an Embed" but then that won't always be correct (e.g. "Add an Category"). Additionally, because you can name the link type whatever you like, we can't plan for every case. 

Might just use "Add Embed".

**Comment by engram-design** [comment]
Added for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.0.5.2"`

**Comment by engram-design** [comment]
Updated in [1.1.0](https://github.com/verbb/hyper/releases/tag/1.1.0)
