### ISSUE TITLE
Updating Link Types resets the selection on save

### ISSUE THREAD

**Issue by aaronbushnell** [verbb/hyper#4]
### Describe the bug

After I configure the Link Types I want active and inactive and save the selections I've made are overridden. Here's a quick video of what happens as I click these and save a couple times:

https://user-images.githubusercontent.com/315202/219043035-e817c57b-d326-4f02-99f9-f812b47fb474.mov

### Steps to reproduce

1. Add a new Hyper field
2. Select/deselect some options
3. Save the field

### Craft CMS version

Craft Pro 4.3.9

### Plugin version

1.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [1.0.1](https://github.com/verbb/hyper/releases/tag/1.0.1)
