### ISSUE TITLE
Selecting an asset results in "Asset not configured with its filename"

### ISSUE THREAD

**Issue by darylknight** [verbb/hyper#40]
### Describe the bug

Now that not being able to select assets is fixed in 1.1.0, I selected an asset for a Hyper field. When I go to either the edit page for that entry, or that entry on the front end, which includes that Hyper field, I get an "Asset not configured with its filename" error.

I have tried re-saving and changing the asset's filename

![image](https://user-images.githubusercontent.com/1250017/223069384-fd14117e-04e1-49da-bba2-2cea429b3251.png)

### Steps to reproduce

1. Add a Hyper field with an asset type
2. Add an asset

### Craft CMS version

4.3.10

### Plugin version

1.0.5

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.0"`

**Comment by darylknight** [comment]
Fixed it, thank you!
