### ISSUE TITLE
Issues adding to "existing" / bootstrapped project

### ISSUE THREAD

**Issue by corneliusio** [verbb/hyper#41]
### Describe the bug

I'm currently looking into this plugin as a replacement for our default go-to, Typed Link Field. We use a slightly bootstrapped version of Craft for all of our projects with some basic fields and plugins we use pretty much all the time and a few sections.

When I setup the new project and run the Typed Link Fields Migration, everything appears to run normally, however, when I attempt to update any configuration below "Link Types: Configure the types of links available for users to pick from." the changes are not saved (Enable New Window, Default New Window, and Enable Multiple Links along with its two text fields do update as expected).

Additionally, the field UI simply will not display in the admin when editing an entry. There are no errors in the console, but it does appear to be a JS issues.
<img width="430" alt="Screenshot 2023-03-01 at 5 05 11 PM" src="https://user-images.githubusercontent.com/4140885/223166397-a205d1d1-3cbb-4e84-b146-63c3d4cb4077.png">

I've checked the site's logs to see if there are any PHP errors there and I can not find anything.

### Steps to reproduce

1. This is the script we use to quickly setup Craft projects with our boilerplate, https://msx.mostlyserious.dev/create:craft. You can also just setup & install the project manually from https://packagist.org/packages/mostlyserious/ms-craft, run `bootstrap/script.sh` found in the project, and finish with `php craft project-config/apply`.
2. Install Hyper and either migrate the existing Typed Link Fields or create a new Hyper field.

### Craft CMS version

4.3.10

### Plugin version

1.1.0

### Multi-site?

No

### Additional context

I have confirmed that this issue does not occur when the project is not bootstrapped. But given that there is a pathway for migrating projects in the plugin and that this is an extremely bare-bones configuration that would fall far short of any real project, it seems reasonable that the plugin should be able to handle it without a problem.

**Comment by engram-design** [comment]
Yeah it certainly seems to be related to JS. The settings of the field for link types are the only things using Vue, the rest is regular Twig. But the link types configuration _does_ show, it just doesn't save anything, correct?

I'll give your boilerplate a go and see if there's anything I can detect from that.

**Comment by engram-design** [comment]
Figured this one out, thanks! Fixed in [1.1.1](https://github.com/verbb/hyper/releases/tag/1.1.1)

**Comment by corneliusio** [comment]
Awesome, thanks for running that down! Everything is looking good on our end now.
