### ISSUE TITLE
Field layout not respected after save

### ISSUE THREAD

**Issue by corneliusio** [verbb/hyper#42]
### Describe the bug

Hey, me again. 😅

It looks like the field layout is not being respected when the field is rendered when editing an entry. I can add, remove, and re-organize the fields under "Content" and "Advanced" without issue, and the layout does save. However, the changes are not reflected when editing an entry with the field.

### Steps to reproduce

1. Create Hyper field
2. Update the default field layout in any way
3. View rendered field 

### Craft CMS version

4.3.10

### Plugin version

1.1.1

### Multi-site?

No

### Additional context

This occurs on both a completely fresh install as well as an existing project. Also, already very excited to start using this plugin based on what I see.

**Comment by engram-design** [comment]
Hmmm, I can't seem to replicate this immediately I'm afraid. Just want to confirm that after saving the field and refreshing the page, going back to check the link types you've modified, everything seems all okay there?

And just to confirm you're picking the right link type in the entry with the modified field layout?

I'm actually still using your bootstrap project to test this as well.

**Comment by corneliusio** [comment]
@engram-design Oh man, I'm sorry—that's on me. I totally didn't realize each type had its own field layout, which honestly just got me so much more excited about how this plugin can be used. Sorry for jumping the gun on creating this issue, it was a hectic day and I was just moving too quickly. I appreciate your time working through the influx of stuff that comes with dropping a new plugin.

**Comment by engram-design** [comment]
No problem at all, I wanted to check that first at least, as it trips up even me sometimes. It's a tricky one, as originally I was going to have just a single field layout for all types, but I knew people would want to customise fields depending on the type.
