### ISSUE TITLE
Add link dropdown doesn't work in live preview

### ISSUE THREAD

**Issue by gglnx** [verbb/hyper#43]
### Describe the bug

The »Add a link« dropdown doesn't work in live preview. I don't see any JavaScript errors in the console.

### Steps to reproduce

1. Open an entry with a multiple link Hyper field and edit in live preview
2. Try to click »Add a link«

### Craft CMS version

4.4.3

### Plugin version

1.1.2

### Multi-site?

No

**Comment by engram-design** [comment]
Likely related to https://github.com/verbb/hyper/issues/44

Should be fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.2"`

**Comment by engram-design** [comment]
Fixed in [1.1.3](https://github.com/verbb/hyper/releases/tag/1.1.3)
