### ISSUE TITLE
z-index issue on "Add a link" button when editing an element in a slideout

### ISSUE THREAD

**Issue by tomdavies** [verbb/hyper#44]
### Describe the bug

Due to a CSS / z-index bug, the "Add a link" button on Hyper fields appears not to work when editing an element in a slideout, as the "link type" selector UI renders behind the element flyout. 

Increasing the z-index of the `data-tippy` element to <=100 makes the link type selector UI visible again

Current code (`z-index: 10`)

<img width="1585" alt="Screenshot 2023-03-20 at 16 54 00" src="https://user-images.githubusercontent.com/136308/226412154-985d8553-395d-442b-994c-7f50db932a0b.png">

With `z-index: 100`:

<img width="1593" alt="Screenshot 2023-03-20 at 16 53 28" src="https://user-images.githubusercontent.com/136308/226412299-b5b6e7b7-8a2c-4209-b794-884a28b3ef84.png">

### Steps to reproduce

1. Create a Hyper field with **Enable Multiple Links** set to "on"
2. Add the Hyper field to an element type
3. Create a new instance of that element type
4. Attempt to edit that instance via a slide out
5. When clicking "add a link" the tippy overlay is added to the DOM, but renders behind the flyout body 
6. Inspecting the  `data-tippy` element and increasing its `z-index` value to 100 makes it visible 

### Craft CMS version

4.4.3

### Plugin version

1.1.2

### Multi-site?

No

**Comment by engram-design** [comment]
Good call. Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.2"`

**Comment by tomdavies** [comment]
🤜🤛 thanks for the quick fix

**Comment by engram-design** [comment]
Fixed in [1.1.3](https://github.com/verbb/hyper/releases/tag/1.1.3)
