### ISSUE TITLE
Access Array Index

### ISSUE THREAD

**Issue by jan-dh** [verbb/hyper#49]
### What are you trying to do?

I have a field (links) that I set in a global set `footer`. Would love to be able to do the following:
```
{% set links = footer.links %}

some random code ....
{{ links[0].url }}
some random code...
{{ links[1].url }}
```

Currently I can't access the array index, it gives me :
```
Twig Runtime Error – Twig\Error\RuntimeError
Impossible to access a key "0" on an object of class "verbb\hyper\models\LinkCollection" that does not implement ArrayAccess interface.
```

### What's your proposed solution?

Make the Array index accessible

**Comment by engram-design** [comment]
Added in [1.1.4](https://github.com/verbb/hyper/releases/tag/1.1.4)
