### ISSUE TITLE
Using `getLink()` does not use the custom "Link Text" content

### ISSUE THREAD

**Issue by aaronbushnell** [verbb/hyper#5]
### Describe the bug

If I select an entry and supply "Link Text" the `{{ field.getLink() }}` function uses the title of the selected element.

### Steps to reproduce

1. Select an Entry for your link
2. Use the `getLink()` function on the front end

### Craft CMS version

Craft Pro 4.3.9

### Plugin version

1.0.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [1.0.2](https://github.com/verbb/hyper/releases/tag/1.0.2).
