### ISSUE TITLE
Example from the documentation not working

### ISSUE THREAD

**Issue by jan-dh** [verbb/hyper#53]
### Describe the bug

The example in the docs found [here](https://verbb.io/craft-plugins/hyper/docs/template-guides/rendering-links#rendering-links)

```
{{ entry.myLinkField.getLink({
    class: 'text-black font-bold',
    'data-link': 'external',
}) }}

{# Outputs: <a href="http://my-site.test/some-url" class="text-black font-bold" data-link="external">Some URL</a> #}
```

doesn't actually work if there's already a class set on the element.

Even trying to merge them like so doesn't work. 

```
{{ entry.myLinkField.getLink({
    class: 'text-black font-bold' ~ " " ~ entry.myLinkField.classes,
    'data-link': 'external',
}) }}
```

Not sure if this works as intended, but the ability to add some custom classes + the ones from the CMS seems the intention here? If not you can relabel this as a Feature request 🙂

### Steps to reproduce

1. Create a new Hyper field & create a link with a class
1. Output the field following the documentation guidelines & try to add a custom class.

```
{{ entry.myLinkField.getLink({
    class: 'text-black font-bold',
    'data-link': 'external',
}) }}
```

### Craft CMS version

 4.4.8

### Plugin version

1.1.4

### Multi-site?

"yes"

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.4"`

**Comment by engram-design** [comment]
Updated in [1.1.5](https://github.com/verbb/hyper/releases/tag/1.1.5)
