### ISSUE TITLE
The URL link's "Placeholder" setting value does not save.

### ISSUE THREAD

**Issue by benjaminkohl** [verbb/hyper#55]
### Describe the bug

When setting up new Hyper fields and configuring the options for a "URL" type link, any value written in the "Placeholder" setting field does not get saved to the field's settings and the placeholder text always shows up as the default (site URL).

### Steps to reproduce

1. Create a new Hyper field in Craft.
2. Specify a Placeholder field value in the URL tab.
3. Save the field settings.
4. Assign the field to an element's corresponding field layout.
5. Open a new/edit form for that element type and observe the placeholder text for a URL type link.

### Craft CMS version

4.4.8

### Plugin version

1.1.4

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.4"`

**Comment by engram-design** [comment]
Updated in [1.1.5](https://github.com/verbb/hyper/releases/tag/1.1.5)
