### ISSUE TITLE
 Is using Crafts build in `relateTo` possible to use with this plugin?

### ISSUE THREAD

**Issue by LeoWie93** [verbb/hyper#56]
### Question

We are currently using the "Typed Link Field" Plugin.
One mayor flaw for us is, that you cant find relations to other entries if they are linked via this typedLinkField Plugin.

For example:
Im saving an entry. Now i want to get all Entries that link / use the saved entry inside their own content.

Is this something that is solved / possible if  we would change over to hyper?

**Comment by engram-design** [comment]
You can't use the built-in `relatedTo` call, because that's only for native Craft stuff. Refer to [getRelatedElements](https://verbb.io/craft-plugins/hyper/docs/template-guides/available-variables#craft-hyper-getRelatedElements)

**Comment by LeoWie93** [comment]
@engram-design am i understanding this correct?

if, for example, we have:
- entry1 with `id 1`
- entry 20 with `id 20`

entry1 is referenced via an hyper field on the entry20.

i could call 
```
{% set relatedElements = craft.hyper.getRelatedElements({
  relatedTo: {
      targetElement: entry, (with id 1)
      field: 'myHyperField',
  },
  ownerSite: 'mySite',
  elementType: 'craft\\elements\\Entry',
)}.all()
```

this would give me the entry with the id 20? 

So the same behavior as Crafts built-in `relatedTo` funtion?
Sry i am doing a lot of stuff right now. if i am to vague or the question is poorly worded please say so.

**Comment by engram-design** [comment]
That would be correct, it's the same behaviour as Craft's `relatedTo`, just a separate function. But this will return all entries that have a Hyper field with the handle `myHyperField` that reference an entry with ID of 1.
