### ISSUE TITLE
Ability to overwrite linkText in Twig

### ISSUE THREAD

**Issue by corneliusio** [verbb/hyper#57]
### What are you trying to do?

There are cases where we use link fields on our site where we hardcode an icon within the anchor tag. In the past we've been using Typed Link Field in combination with a macro to help with this among other conveniences. The macros allows for `prepend` and `append` options to be passed and, if they're present, update the link text before output. 

(I know there are some adjustments to be made here to work with Hyper)

```twig
{% macro link(button, args = {}, wrap = false) %}
    {% if button and not button.isEmpty %}
        {% if args.prepend is defined %}
            {% set args = args|merge({ text: "#{args.prepend}#{button.text}" }) %}
        {% endif %}
        {% if args.append is defined %}
            {% set args = args|merge({ text: "#{button.text}#{args.append}" }) %}
        {% endif %}
        {% if wrap %}
            {{ tag(wrap, { html: button.link(args) }) }}
        {% else %}
            {{ button.link(args) }}
        {% endif %}
    {% endif %}
{% endmacro %}
```

I know that we could simply write the anchor tag manually, make a call to `getLinkAttributes`, and output the appended or prepended content in the template ourselves along side the `text`, but it would be really convenient to simply pass an argument to the `getLink` call that would overwrite the text.

### What's your proposed solution?

Either passing an option like this:

```twig
{{ block.linkField.getLink({
    linkText: 'FOOBAR'
}) }}
```

or a `setLinkText` method that could overwrite this separately.

```twig
block.linkField.setLinkText('FOOBAR')
block.linkField.getLink()
```

Personally I think the first is easier to work with, but understand that the arguments being passed to `getLink` are technically for attributes so could understand not wanting to mix `linkText` in the mix.

**Comment by engram-design** [comment]
Didn't actually realise you _couldn't_ do this, so just an oversight on my part. Added for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.4"`

**Comment by corneliusio** [comment]
Ah, fantastic! Sounds good, thank you.

**Comment by engram-design** [comment]
Updated in [1.1.5](https://github.com/verbb/hyper/releases/tag/1.1.5)
