### ISSUE TITLE
Null value on elementType causing empty modal

### ISSUE THREAD

**Issue by jimirobaer** [verbb/hyper#58]
### Describe the bug

I am running into a weird issue using Hyper on an **existing project**. The modal that appears when clicking the 'Choose' button on an Entry (or Category, or any type that triggers the modal) results in that modal being empty.

Looking at the request, I noticed that the `elementType` parameter that in the request to open the modal is set to `null`. This should not be null, as the error message implies ("Request missing required param").

I was suspecting a conflict with a specific plugin, but even after disabling _every_ plugin, I still run into this issue. I have also cleared all necessary caches in between steps just to be sure.

I can confirm the issue is not caused by my local development environment, as I have pushed this project to a server resulting in the same behavior. I also don't have issues opening modals from built-in Craft fields, like the Entries field.

I have no idea what is causing this and I am also unsure how to proceed. Would it be helpful that I send you the project I am working on (Project Config + Composer) so you can see for yourself? 

### Steps to reproduce

I haven't found the root cause, but I have been trying to fix and/or debug it:

1. Disabling and removing all plugins except Hyper.
2. Dumping the contents`Link` object in `vendor/verbb/hyper/src/templates/links/_element/input.html` to see if there's an elementType with a different value than `null` there (it is not).
3. Rebuilding my config from the database.

There are no logs about anything that might be related to this issue.

### Craft CMS version

4.4.10.1

### Plugin version

1.1.4

### Multi-site?

Yes

### Additional context

The inline <script> tag added for each instance of a Hyper field, with elementType being set to `null`:

```
new Craft.BaseElementSelectInput({
   "id":"fields-entriesLink-0-link-url-1524789403",
   "name":"fields[entriesLink][0][linkValue]",
   "elementType":null,
   "sources":[
      "section:4a93fd40-fc6e-4c27-b9d4-9ffeba8b0fa1"
   ],
   "condition":null,
   "referenceElementId":null,
   "referenceElementSiteId":null,
   "criteria":{
      "status":null,
      "uri":":notempty:"
   },
   "allowSelfRelations":false,
   "maintainHierarchy":false,
   "branchLimit":null,
   "sourceElementId":null,
   "disabledElementIds":null,
   "viewMode":"list",
   "single":false,
   "limit":1,
   "showSiteMenu":true,
   "modalStorageKey":"hyper.entriesLink.entry",
   "fieldId":null,
   "sortable":true,
   "prevalidate":false,
   "modalSettings":{
      "modalTitle":"Choose"
   }
});
```

The request returning a 400 Bad Request status code: 

```
{
   "context":"modal",
   "elementType":null,
   "sources":[
      "section:4a93fd40-fc6e-4c27-b9d4-9ffeba8b0fa1"
   ],
   "showSiteMenu":"1"
}
```

**Comment by engram-design** [comment]
That does seem quite odd. Did you migrate the Hyper link field from another link plugin, or just created from scratch?

If you wouldn't mind sharing your project config Yaml file for the Hyper field in question, you can add here, or send through to `support@verbb.io`.

**Comment by engram-design** [comment]
As some more debugging, try adding the following to the `vendor/verbb/hyper/src/templates/links/_element/input.html`

```twig
{{ dump(link.elementType) }}
{{ dump(link.elementType()) }}
{{ dump(className(link)) }}
```

It seems _very_ strange this it can't resolve the element type of the `verbb\hyper\links\Entry` class, which is [statically defined](https://github.com/verbb/hyper/blob/8a36f56d02560822cfff716b1549560af7902e65/src/links/Entry.php#L15)

**Comment by jimirobaer** [comment]
Dumping these in order returns:

```
null
"craft\elements\Entry"
"verbb\hyper\links\Entry"
```

Oddly, the `link.elementType()` function does return the proper value. Changing line 26 in the file from `elementType: link.elementType` to `elementType: link.elementType()` seems to solve the issue.

**Comment by engram-design** [comment]
How interesting! I was also testing out different PHP versions, 8.0 through to 8.2 just in case it was this specific issue. What's your PHP version? That's certainly an easy change for me, but would be nice to figure out _why_ there's the discrepancy (those render correctly for me).

**Comment by engram-design** [comment]
Updated in [1.1.5](https://github.com/verbb/hyper/releases/tag/1.1.5)

**Comment by jimirobaer** [comment]
I tried on 8.0, 8.1 and 8.2 both locally and on the server, with the same result. But glad that this was an easy fix, even if I don't understand what is causing it.
