### ISSUE TITLE
Docs: Incorrect event name in example

### ISSUE THREAD

**Issue by chrismlusk** [verbb/hyper#59]
### Describe the bug

The example in the docs for [registering your own link type](https://verbb.io/craft-plugins/hyper/docs/developers/link-type#link-type) has the wrong constant.

`Links::EVENT_REGISTER_SOURCE_TYPES`

I believe it should be:

`Links::EVENT_REGISTER_LINK_TYPES`

### Steps to reproduce

1. 
2. 

### Craft CMS version

4x

### Plugin version

1.1

**Comment by engram-design** [comment]
Good call, updated.
