### ISSUE TITLE
Problems after uninstalling Craft Commerce

### ISSUE THREAD

**Issue by alexanderloewe** [verbb/hyper#65]
### Describe the bug

After I uninstalled Craft Coerce, we get the following error, by opening the Hyper Field

<img width="1688" alt="Bildschirmfoto 2023-05-28 um 20 15 24" src="https://github.com/verbb/hyper/assets/69263307/297729b3-cd62-4f35-9b00-6367a644adff">

You would have to customize Hyper to remove the appropriate records when a plugin is uninstalled.

### Steps to reproduce

1. Install Craft Commerce
2. Uninstall Craft Commerce
3. Try to open the Hyper Field

### Craft CMS version

Craft CMS 4.4.13

### Plugin version

1.1.7

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.7"`

**Comment by alexanderloewe** [comment]
Thanks

**Comment by engram-design** [comment]
Fixed in [1.1.8](https://github.com/verbb/hyper/releases/tag/1.1.8)
