### ISSUE TITLE
Field instructions not working

### ISSUE THREAD

**Issue by strandofgenius** [verbb/hyper#67]
### Describe the bug

I have added instructions to the Hyper ARIA label field which doesn't display when editing an entry.

<img width="678" alt="Screen Shot 2023-06-06 at 9 21 46 AM" src="https://github.com/verbb/hyper/assets/11370639/acdf5d06-0f1c-4e81-b8a1-b888def90522">

<img width="723" alt="Screen Shot 2023-06-06 at 9 22 27 AM" src="https://github.com/verbb/hyper/assets/11370639/23974917-7bab-441d-81f2-0357bbee3296">

### Steps to reproduce

1. Create a Hyper field with an ARIA label
2. Add some instructions to the ARIA label
3. Assign to an entry type

### Craft CMS version

4.4.13

### Plugin version

1.1.7

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.7"`

**Comment by engram-design** [comment]
Fixed in [1.1.8](https://github.com/verbb/hyper/releases/tag/1.1.8)
