### ISSUE TITLE
Removing an entry selection causes field to pull first entry in Craft instead of `null`

### ISSUE THREAD

**Issue by aaronbushnell** [verbb/hyper#7]
### Describe the bug

If you use an Entry selection (perhaps the same is true for other relationship-based selections) and then you remove that selection Hyper will not return `null` as expected. Instead, it will simply query the first entry from Craft and begin returning that.

### Steps to reproduce

1. Make an "Entry" selection
2. Save the entry
3. Remove the selection
4. Resave the entry
5. The field will return the most recent entry instead of returning `null`

### Craft CMS version

Craft Pro 4.3.9

### Plugin version

1.0.2

### Multi-site?

No

**Comment by engram-design** [comment]
🤦‍♂️ Silly mistake on my part there. 

Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-4 as 1.0.2"`

**Comment by aaronbushnell** [comment]
Thanks, @engram-design! ❤️

**Comment by engram-design** [comment]
Fixed in [1.0.3](https://github.com/verbb/hyper/releases/tag/1.0.3).
