### ISSUE TITLE
Create links programatically.

### ISSUE THREAD

**Issue by samuelbirch** [verbb/hyper#70]
### Question

Whats the best way to create links programmatically either via a plugin/module or migration.

I'm currently try to create them passing in an array to the element->setFieldValue() method.

**Comment by engram-design** [comment]
Best to create a link model to be used as the value of the field.

```php
$value = new \verbb\hyper\links\Url();
$value->linkText = ‘some text’;
$value->linkValue = ‘http://…’;
Etc…

$element->setFieldValue(‘hyperHandle’, [$value]);
```

where the type is one of https://github.com/verbb/hyper/tree/craft-4/src/links you can check for all the necessary properties in those classes, or inherited from https://github.com/verbb/hyper/blob/craft-4/src/base/Link.php

**Comment by samuelbirch** [comment]
is it possible to do it as an array, because i have the field as part of a matrix field which is getting created like so:

```
'matrixFieldHandle' => [
    'blocks' => [
        'new1' => [
            'type' => 'myType',
            'fields' => [
                'hyperFieldHandle' => [
                    'type' => 'verbb\\hyper\\links\\Product',
                    'linkValue' => 1,
                ]
            ]
        ]
    ]
]
```

**Comment by engram-design** [comment]
That should also be fine, just bear in mind (and my adjusted example) that links are always stored as a collection.

The `type` should also refer to the link type which as there can be multiple is a little special.

```
handle => ‘default-’ . \craft\helpers\ StringHelper::toKebabCase(\verbb\hyper\links\Product::class)
```

see https://github.com/verbb/hyper/blob/craft-4/src/integrations/feedme/fields/Hyper.php

**Comment by samuelbirch** [comment]
I've got this but its not working.

```
"hyperFieldHandle" => [
              "handle" => "default-verbb-hyper-links-product",
              "linkValue" => 89801,
]
```

**Comment by engram-design** [comment]
Should still be an array of content, so
```
"hyperFieldHandle" => [
[
              "handle" => "default-verbb-hyper-links-product",
              "linkValue" => 89801,
]
]
```

I’ll double check on a computer tomorrow if that’s still not working. Another reference https://github.com/verbb/hyper/blob/ed96396ee2fc64da31d901b2a6e7aa18d04e0f00/src/migrations/MigrateLinkitContent.php#L71

**Comment by samuelbirch** [comment]
yeah, just figured that one out!

just having trouble setting the linkValue to an elementId now.

**Comment by engram-design** [comment]
This should be how you can use array syntax:

```php
$entry = \craft\elements\Entry::find()->id(123)->one();

$entry->setFieldValues([
    'matrixFieldHandle' => [
        'new1' => [
            'type' => 'blockTypeHandle',
            'fields' => [
                'hyperFieldHandle' => [
                    'links' => [
                        'type' => 'verbb\\hyper\\links\\Entry',
                        'handle' => 'default-verbb-hyper-links-entry',
                        'linkValue' => 123,
                    ],
                ],
            ],
        ],
    ],
]);

Craft::$app->getElements()->saveElement($entry);
```

**Comment by samuelbirch** [comment]
all good now - was my mistake, i was using the Product link type but passing in a variant Id
