### ISSUE TITLE
Custom attributes are not rendering

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [verbb/hyper#80]
### Describe the bug

So im using the following code to render the button:
`{{ entry.button.getLink({class: 'btn btn-dark'}) }}`
Which results in 
<a class="btn btn-dark" href="https://link.com" rel="noopener noreferrer" target="_blank">Bekijk de website</a>
With these settings:
![Screenshot 2023-07-20 at 09 19 42](https://github.com/verbb/hyper/assets/50947605/05679aaf-d5bb-4822-a780-7a810c5ad3c5)
It seems our custom attributes setting is somehow overwritten? We want rel="nofollow"

### Steps to reproduce

1. Render a button with the following code: `{{ entry.button.getLink({class: 'btn btn-dark'}) }}`
2. Set rel nofollow in the settings.

### Craft CMS version

4.4.15

### Plugin version

1.1.9

### Multi-site?

Yes

### Additional context

Dumping the field does shows it does contain the data: 
```
customAttributes: array:1 [▼
    0 => array:2 [▼
      "attribute" => "rel"
      "value" => "nofollow"
    ]
  ]
```

**Comment by engram-design** [comment]
I can't seem to replicate that, sorry! Here's my details

<img width="608" alt="image" src="https://github.com/verbb/hyper/assets/1221575/82d9ea4a-94b7-4128-af29-99bb31350add">
<img width="625" alt="image" src="https://github.com/verbb/hyper/assets/1221575/a0171137-11fc-43c3-9eb5-65aaaf30b84e">

Produces the following HTML

```html
<a class="btn btn-dark" href="https://github.com/" rel="nofollow">https://github.com/</a>
```

Is there something different on your end, maybe? I will mention that if you have "New Window" enabled, that will override any custom attributes you have set for `rel` (we add `rel="noopener noreferrer"` for links that open in a new window).

**Comment by bob-pixeldeluxe** [comment]
Ah sorry, I did another test and i only have this problem with the new window option checked. Without I get a correct output.

**Comment by engram-design** [comment]
Right, that makes sense now! That's an interesting one, as `rel` attributes aren't treated like `class` attributes, where they can be merged. We actually just use Craft's `normalizeTagAttributes()` function to handle that, so we'll need to extend that.

Should be updated for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.9"`

**Comment by bob-pixeldeluxe** [comment]
Great thanks!

**Comment by engram-design** [comment]
Updated in [1.1.10](https://github.com/verbb/hyper/releases/tag/1.1.10)
