### ISSUE TITLE
Can't make any change (e.g. add new link types) to existing Hyper field

### ISSUE THREAD

**Issue by bossanova808** [verbb/hyper#82]
### Describe the bug

I am trying to add two new link types to an existing Hyper field, which is used in a Matrix.

The Hyper field offers Asset, Entry, and Category link types.  I want to add Product and Variant to this.

When I do this I get the error:

```
Error: Typed property craft\fields\Matrix::$contentTable must not be accessed before initialization in /home/forge/imagescience.com.au/releases/dev/vendor/yiisoft/yii2/base/Model.php:719
Stack trace:
#0 /home/forge/imagescience.com.au/releases/dev/vendor/yiisoft/yii2/base/Model.php(1007): yii\base\Model->getAttributes()
#1 [internal function]: yii\base\Model->getIterator()
#2 /home/forge/imagescience.com.au/releases/dev/vendor/twig/twig/src/Extension/CoreExtension.php(1252): iterator_count(Object(craft\fields\Matrix))
#3 /home/forge/imagescience.com.au/releases/dev/storage/runtime/compiled_templates/0e/0e3e3d97b7b68da2f5bdfb39ccd097eb.php(51): twig_test_empty(Object(craft\fields\Matrix))
#4 /home/forge/imagescience.com.au/releases/dev/vendor/twig/twig/src/Template.php(394): __TwigTemplate_d7ccb57ca2631190ae090ad31b129b46->doDisplay(Array, Array)
#5 /home/forge/imagescience.com.au/releases/dev/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /home/forge/imagescience.com.au/releases/dev/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#7 /home/forge/imagescience.com.au/releases/dev/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#8 /home/forge/imagescience.com.au/releases/dev/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#9 /home/forge/imagescience.com.au/releases/dev/vendor/craftcms/cms/src/web/View.php(465): Twig\Environment->render('...', Array)
#10 /home/forge/imagescience.com.au/releases/dev/vendor/craftcms/cms/src/web/View.php(518): craft\web\View->renderTemplate('...', Array)
#11 /home/forge/imagescience.com.au/releases/dev/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\web\View->renderPageTemplate('...', Array, '...')
#12 /home/forge/imagescience.com.au/releases/dev/vendor/yiisoft/yii2/web/Response.php(1098): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#13 /home/forge/imagescience.com.au/releases/dev/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#14 /home/forge/imagescience.com.au/releases/dev/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#15 /home/forge/imagescience.com.au/releases/dev/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#16 /home/forge/imagescience.com.au/releases/dev/web/index.php(12): yii\base\Application->run()
#17 {main}
```

### Steps to reproduce

Add new link types to existing Hyper field in a matrix

### Craft CMS version

Craft Pro 4.4.16.1

### Plugin version

dev-craft-4

### Multi-site?

No

### Additional context

In testing it appears if I try to make _any_ change to this field I get this error.

This field was a Typed Link Field prior to the upgrade to Hyper, I believe.

I do not currently have a workaround...

**Comment by engram-design** [comment]
Just to clarify, this error appears when you edit the Hyper field, not when editing an entry that contains a Hyper field - correct?

If so, I can't seem to replicate this, no matter what I do to modifying the settings of the field. Wondering if you might be able to share your Matrix field setup? Maybe something has messed up in the conversion from Typed link?

**Comment by bossanova808** [comment]
Yep as soon as I change literally anything about the field (e.g. changing default link type from URL -> Entry, same error).

In terms of setup - what would help?  Project config, screenshot, or...?

There's not a lot to this one...as far as Matrix fields go it's a simple one...previously I needed the separate 'Variant' field here to occasionally link a specific variant, but with Hyper it can (and should) be combined into that.

![image](https://github.com/verbb/hyper/assets/731309/ffe19375-b269-4495-87d1-390337c01d6e)

**Comment by engram-design** [comment]
Alright, so took a while to get to the bottom of this one!

Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.10"`

**Comment by bossanova808** [comment]
This appears to be working with your changes - thanks Josh, you're a legend.
