### ISSUE TITLE
Lightswitch and Asset fields problems when saving.

### ISSUE THREAD

**Issue by leowebguy** [verbb/hyper#85]
### Describe the bug

Tried different ways and found a workaround, but I think it's worth reporting it.

1. Lightswitch won't work if placed in the "Content" tab, click doesn't "switch" the Lightswitch; It does work when placed in "Advanced" tab.

2. The Asset field has the same problem, but the other way around... only works on "Content" tab, if placed in the "Advanced" tab, it won't pick up the asset, no matter what...

So I ended up having to organize my custom fields like this...

<img width="685" alt="Screenshot 2023-08-09 at 12 09 19 PM" src="https://github.com/verbb/hyper/assets/8460020/51930e39-238b-4a2a-8635-05d5ebcb257c">

### Steps to reproduce

1. Create two custom fields, 1. Lightswitch 2. Asset
2. Add them to the Hyper link, Lightswitch into "Content" tab and the "Asset" into "Advanced" tab
3. Try to activate the Lightswitch
4. Try to add asset to Field and save the entry

### Craft CMS version

4.4.17

### Plugin version

1.1.10

### Multi-site?

No

### Additional context

N/A

**Comment by engram-design** [comment]
Fixed in [1.1.11](https://github.com/verbb/hyper/releases/tag/1.1.11)
