### ISSUE TITLE
Phone validation incorrect

### ISSUE THREAD

**Issue by howells** [verbb/hyper#86]
### Describe the bug

I can't work at out at all from the docs or from trial and error what the format for a Phone link should be. I've tried 07976399087, +447976399087, tel:+447976399087, tel:447976399087 etc which are all valid UK phone numbers but none of which are accepted showing "Please enter a valid phone number."

### Steps to reproduce

1. Enter any valid UK phone number.
2. Submit.

### Craft CMS version

4.5.0

### Plugin version

1.1.11

### Multi-site?

No

**Comment by engram-design** [comment]
Both seem to work for me! 
<img width="224" alt="image" src="https://github.com/verbb/hyper/assets/1221575/f140acc1-0983-4d92-9ceb-165467c344b8">

<img width="268" alt="image" src="https://github.com/verbb/hyper/assets/1221575/fb1db368-3117-48e9-9d33-65f359029fb1">

The validation is pretty loose so we can cater for a variety of different numbers around the world. The regex we use is `/^[0-9+\(\)#\.\s\/ext-]+$/` and you can verify that with a tool like https://regex101.com to see the matches. Here's some quick test cases https://regex101.com/r/i6T9SS/1

**Comment by howells** [comment]
@engram-design now seems to work completely fine; I can't think what the circumstance would be where the field would be invalidated. Perhaps a hidden character crept in there.

**Comment by howells** [comment]
@engram-design ah, cut and paste from Apple's contacts: had U+202D and U+202C characters either side

**Comment by engram-design** [comment]
Oh! Well that’s quite interesting, I’ll check that out
