### ISSUE TITLE
Field handles dont show up on custom fields

### ISSUE THREAD

**Issue by piotrpog** [verbb/hyper#88]
### Describe the bug

When we add custom fields to hyper field layout (for example, text field), their handles do not show up in element edit view. 
I checked it with "Show field handles in edit forms" option enabled for logged in user.

### Steps to reproduce

1. Create hyper field
2. Add custom field to hyper field layout
3. Custom field handle does not show when editing entry containing hyper field

### Craft CMS version

4.3.5

### Plugin version

1.1.12

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.12"`

**Comment by engram-design** [comment]
Fixed in [1.1.13](https://github.com/verbb/hyper/releases/tag/1.1.13)
