### ISSUE TITLE
Some texts aren't translated

### ISSUE THREAD

**Issue by FrDH** [verbb/hyper#89]
### Describe the bug

I was trying to add some translations but found the following phrases aren't being translated:
- Custom
- Email
- Settings
- Delete
- e.g. Read more

### Steps to reproduce

1. Add a new translation file for the current language, in my case `translations/nl/hyper.php`
2. Add a translation for "e.g. Read more", in Dutch this would be "b.v. Lees meer"
3. Edit a Hyper field on a page, the link text field will show "e.g. Read more", not "b.v. Lees meer".

Just FYI, I had a look at the code and it looks like this should have worked:
https://github.com/verbb/hyper/blob/0fa0ebfccc2ace6be5a8e96841658eec9ba06f27/src/fieldlayoutelements/LinkTextField.php#L31
Any idea's on why it isn't tranlated?

### Craft CMS version

4.5

### Plugin version

1.1.12

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.12"`

**Comment by engram-design** [comment]
Fixed in [1.1.13](https://github.com/verbb/hyper/releases/tag/1.1.13)
