### ISSUE TITLE
Very large project config generation

### ISSUE THREAD

**Issue by aaronbushnell** [verbb/hyper#9]
### Describe the bug

I noticed in a pull request that the project config files for Hyper fields are quite large. Are these possibly generating errant or extraneous info? The first three collapsed files are going from a Typed Link Field to a Hyper fieldtype.

<img width="852" alt="Screenshot 2023-02-15 at 10 03 24 PM" src="https://user-images.githubusercontent.com/315202/219257517-737b76cf-82d8-4075-864a-2f8c8738cfa7.png">

### Steps to reproduce

1. Create a Hyper field with project config enabled
2. Open generated `.yaml` file for the newly created field

### Craft CMS version

Craft Pro 4.3.9

### Plugin version

1.0.2

### Multi-site?

No

**Comment by engram-design** [comment]
This is somewhat unavoidable because each Hyper field contains a field layout for each link type, and the field layout contains what fields/UI elements/etc to use. It's stored in project config so that they can be created on all other environments pushed to.

**Comment by aaronbushnell** [comment]
As in they have their own field layout configuration and that's what's stored here? Makes sense, @engram-design! Maybe some sort of future optimization could be considered, but that answers my question on if this was a bug or not!

**Comment by engram-design** [comment]
@aaronbushnell That's correct, they can be a little bit large, even if you only have a few fields, but it's vital info. 

They are stored as a YAML associated array object, which they very much don't need to be. This only adds to the size of the YAML file, where it could be just serialized JSON. That should cut down on the filesize, but regardless, everything that's in there needs to be there. It's the price for more flexibility compared to other link fields.

**Comment by aaronbushnell** [comment]
That makes sense, thanks for the clarification! (Awesome work on this, by the way!)

**Comment by croxton** [comment]
Bloated PC files caused by Hyper fields may to be a contributing cause to some significant problems we have seen with rebuilding PC cache data: https://github.com/craftcms/cms/issues/13164

Is there any way to reduce this?

**Comment by croxton** [comment]
I note that field layouts are stored for Link Types that are disabled - could those be left out? The default field layout for a link type could also be simplified to just one tab and a couple fields (looks like we don't often customise those often anyway), and that by itself would significantly reduce the file size if, like us, the layout is infrequently changed from the default.

**Comment by engram-design** [comment]
Hmm trysts a possibility, but it’s not ideal. It means that you’d lose any field layout setting for any link type that’s disabled, which would make users think it’s not working. Maybe part of the UI would need to hide all the settings for a link type when it’s disabled. That would mean you’re not able to change settings unless it’s enabled, and things are reset as soon as you disable a link type.

Still, I think that’d be more annoying to users than anything who don’t want to lose their link type settings, just disable them even temporarily.

I’ll see if there some alternatives…

**Comment by croxton** [comment]
> It means that you’d lose any field layout setting for any link type that’s disabled, which would make users think it’s not working.

I wouldn't expect my field layout settings to be retained if I disabled a field type and pressed save. I think that feels like an expected behaviour, no?

**Comment by engram-design** [comment]
> I wouldn't expect my field layout settings to be retained if I disabled a field type and pressed save. I think that feels like an expected behaviour, no?

If I can edit the settings and then hit save, I would expect my changes to be saved - no matter if it's enabled or not. Imagine editing the field layout of a link type that's disabled and adding some custom fields. If I hit save and go back to look at the link type settings, and my changes have been discarded, that seems like terrible UX and makes the user think something has gone wrong.

Which was the reason for my suggestion that you probably _shouldn't_ be able to edit any of the settings of a disabled link type, for this reason.

I'm also going to look at how we might be able to chunk field layout data up with project config files (if possible) to maybe ease things.

**Comment by croxton** [comment]
@engram-design got some promising results removing the default 'Advanced' tab:
https://github.com/craftcms/cms/issues/13164#issuecomment-1677031999

**Comment by engram-design** [comment]
Great to know, I'll be digging into some solutions soon!

**Comment by jeroenlammerts** [comment]
This still feels too bloated. For a standard use case the advanced tab is not needed and adds way to much yaml to the project.

We use this solution for now, having to delete the advanced tab 10 times for every hyper field!
https://github.com/verbb/hyper/issues/9#issuecomment-1677037944
