### ISSUE TITLE
Re-ordering issues

### ISSUE THREAD

**Issue by stevendierick** [verbb/hyper#93]
### Describe the bug

There's an issue with re-ordering links since 1.1.13. It behaves exactly like the [nesting issue](https://github.com/verbb/hyper/issues/66) we've had before but now on both the parent and nested level. Works fine on 1.1.12. 

So, after re-ordering and saving it will set the link to a different one. When deleting a link, it'll duplicates an existing one. The same issue when nesting Hyper (in both slideout and nesting on parent level). I'm guessing this will also be an issue when using it with Super Table, Neo, Matrix, etc. as I've already experienced it with Vizy.

There's also an issue when re-ordering non-entry types, such as an email. It loses its value and inserts its ID instead, I think.

Came across this on a project where I was using Hyper inside a Vizy block. Downgraded back to 1.1.12 to double-check, and also tested it on a fresh install with only Hyper installed.

1) Parent:
   https://share.cleanshot.com/PkB2c10PWNXL2ys9VcYp

2) Parent, nested via slideout, email:
   https://share.cleanshot.com/3rMllC9LW858bFnyjfkm

3) Parent, nested on parent level:
   https://share.cleanshot.com/Vcwmnq0qbpMLVmBwRVYS

4) Parent, nested on parent level, email:
   https://share.cleanshot.com/0zmjCD17Lbg58MHCBLPt

### Steps to reproduce

1. Create Hyper fields
2. Nest Hyper fields (via slideout and/or parent)
3. Add links on parent level
4. Add links on nested level
5. Add email type link
6. Save
7. Re-order links
8. Delete links
9. Save

### Craft CMS version

4.5.5

### Plugin version

1.1.13

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.13"`

**Comment by stevendierick** [comment]
Thanks, that does indeed fix the re-ordering on both parent and nested!

**Comment by engram-design** [comment]
Fixed in [1.1.14](https://github.com/verbb/hyper/releases/tag/1.1.14)
