### ISSUE TITLE
Empty settings and error "HTTP 400 – Bad Request" when we try to save them

### ISSUE THREAD

**Issue by piotrpog** [verbb/hyper#94]
### Describe the bug

When i enter plugin settings, i am shown "No settings available." message, yet "save" button is visible on the top right. When i click this button, error "HTTP 400 – Bad Request" shows up.

### Steps to reproduce

1. enter settings
2. they are empty, try saving
3. error 400

### Craft CMS version

4.5.6 

### Plugin version

1.1.13

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.13"`

**Comment by engram-design** [comment]
Fixed in [1.1.14](https://github.com/verbb/hyper/releases/tag/1.1.14)
