### ISSUE TITLE
Using an Asset field inside a multi-button Hyper field doesn't save the asset relation

### ISSUE THREAD

**Issue by darylknight** [verbb/hyper#97]
### Describe the bug

The design I'm trying to build looks like this:

![image](https://github.com/verbb/hyper/assets/1250017/f3ef0193-a325-41ae-9aec-870e6660723f)

I've set this up as a single Hyper field that allows multiple buttons, created an Asset field called "Button - Icon", then added that to the Hyper layout when selecting a URL, using a new tab:

![image](https://github.com/verbb/hyper/assets/1250017/fd97d1ee-7748-42bd-b6bf-2ab865f1d847)

When you click the cog wheel on one of those buttons, it opens a slideout to select the asset:

![image](https://github.com/verbb/hyper/assets/1250017/c4a390aa-6038-4fb6-96bf-08a55e93cb21)

When you close that slideout, the selected asset disappears and is not saved

### Steps to reproduce

Steps in the list above

### Craft CMS version

4.5.6.1

### Plugin version

1.1.15

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.15"`

**Comment by darylknight** [comment]
Thanks :)

**Comment by darylknight** [comment]
Confirming this fixes it

**Comment by engram-design** [comment]
Fixed in [1.1.16](https://github.com/verbb/hyper/releases/tag/1.1.16)
